/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 4.2 */
/* /usr/local/diamond/3.11_x64/ispfpga/bin/lin64/scuba -w -n mult2 -lang verilog -synth lse -bus_exp 7 -bb -arch sa5p00 -type dspmult -widtha 36 -widthb 36 -widthp 72 -area -signed -rega -regaclk CLK0 -regace CE0 -regarst RST0 -regb -regbclk CLK0 -regbce CE0 -regbrst RST0 -pipe_full -regp -regpclk CLK0 -regprst RST0 -regpce CE0 -rego -regoclk CLK0 -regorst RST0 -regoce CE0 -enable_sync -clk0 -ce0 -rst0 -fdc /home/ross/Programming/FPGA/ECPDiamond/c1/mult2/mult2.fdc  */
/* Tue Apr 28 13:46:11 2020 */


`timescale 1 ns / 1 ps
module ymult2 (CLK0, CE0, RST0, A, B, P)/* synthesis NGD_DRC_MASK=1 */;
    input wire CLK0;
    input wire CE0;
    input wire RST0;
    input wire [35:0] A;
    input wire [35:0] B;
    output wire [71:0] P;

    wire mult2_alu_signedcin_1_0;
    wire mult2_alu_in_cin_1_0_53;
    wire mult2_alu_in_cin_1_0_52;
    wire mult2_alu_in_cin_1_0_51;
    wire mult2_alu_in_cin_1_0_50;
    wire mult2_alu_in_cin_1_0_49;
    wire mult2_alu_in_cin_1_0_48;
    wire mult2_alu_in_cin_1_0_47;
    wire mult2_alu_in_cin_1_0_46;
    wire mult2_alu_in_cin_1_0_45;
    wire mult2_alu_in_cin_1_0_44;
    wire mult2_alu_in_cin_1_0_43;
    wire mult2_alu_in_cin_1_0_42;
    wire mult2_alu_in_cin_1_0_41;
    wire mult2_alu_in_cin_1_0_40;
    wire mult2_alu_in_cin_1_0_39;
    wire mult2_alu_in_cin_1_0_38;
    wire mult2_alu_in_cin_1_0_37;
    wire mult2_alu_in_cin_1_0_36;
    wire mult2_alu_in_cin_1_0_35;
    wire mult2_alu_in_cin_1_0_34;
    wire mult2_alu_in_cin_1_0_33;
    wire mult2_alu_in_cin_1_0_32;
    wire mult2_alu_in_cin_1_0_31;
    wire mult2_alu_in_cin_1_0_30;
    wire mult2_alu_in_cin_1_0_29;
    wire mult2_alu_in_cin_1_0_28;
    wire mult2_alu_in_cin_1_0_27;
    wire mult2_alu_in_cin_1_0_26;
    wire mult2_alu_in_cin_1_0_25;
    wire mult2_alu_in_cin_1_0_24;
    wire mult2_alu_in_cin_1_0_23;
    wire mult2_alu_in_cin_1_0_22;
    wire mult2_alu_in_cin_1_0_21;
    wire mult2_alu_in_cin_1_0_20;
    wire mult2_alu_in_cin_1_0_19;
    wire mult2_alu_in_cin_1_0_18;
    wire mult2_alu_in_cin_1_0_17;
    wire mult2_alu_in_cin_1_0_16;
    wire mult2_alu_in_cin_1_0_15;
    wire mult2_alu_in_cin_1_0_14;
    wire mult2_alu_in_cin_1_0_13;
    wire mult2_alu_in_cin_1_0_12;
    wire mult2_alu_in_cin_1_0_11;
    wire mult2_alu_in_cin_1_0_10;
    wire mult2_alu_in_cin_1_0_9;
    wire mult2_alu_in_cin_1_0_8;
    wire mult2_alu_in_cin_1_0_7;
    wire mult2_alu_in_cin_1_0_6;
    wire mult2_alu_in_cin_1_0_5;
    wire mult2_alu_in_cin_1_0_4;
    wire mult2_alu_in_cin_1_0_3;
    wire mult2_alu_in_cin_1_0_2;
    wire mult2_alu_in_cin_1_0_1;
    wire mult2_alu_in_cin_1_0_0;
    wire mult2_alu_signedr_2_1;
    wire mult2_alu_output_r_2_1_53;
    wire mult2_alu_output_r_2_1_52;
    wire mult2_alu_output_r_2_1_51;
    wire mult2_alu_output_r_2_1_50;
    wire mult2_alu_output_r_2_1_49;
    wire mult2_alu_output_r_2_1_48;
    wire mult2_alu_output_r_2_1_47;
    wire mult2_alu_output_r_2_1_46;
    wire mult2_alu_output_r_2_1_45;
    wire mult2_alu_output_r_2_1_44;
    wire mult2_alu_output_r_2_1_43;
    wire mult2_alu_output_r_2_1_42;
    wire mult2_alu_output_r_2_1_41;
    wire mult2_alu_output_r_2_1_40;
    wire mult2_alu_output_r_2_1_39;
    wire mult2_alu_output_r_2_1_38;
    wire mult2_alu_output_r_2_1_37;
    wire mult2_alu_output_r_2_1_36;
    wire mult2_alu_output_r_2_1_35;
    wire mult2_alu_output_r_2_1_34;
    wire mult2_alu_output_r_2_1_33;
    wire mult2_alu_output_r_2_1_32;
    wire mult2_alu_output_r_2_1_31;
    wire mult2_alu_output_r_2_1_30;
    wire mult2_alu_output_r_2_1_29;
    wire mult2_alu_output_r_2_1_28;
    wire mult2_alu_output_r_2_1_27;
    wire mult2_alu_output_r_2_1_26;
    wire mult2_alu_output_r_2_1_25;
    wire mult2_alu_output_r_2_1_24;
    wire mult2_alu_output_r_2_1_23;
    wire mult2_alu_output_r_2_1_22;
    wire mult2_alu_output_r_2_1_21;
    wire mult2_alu_output_r_2_1_20;
    wire mult2_alu_output_r_2_1_19;
    wire mult2_alu_output_r_2_1_18;
    wire mult2_alu_output_r_2_1_17;
    wire mult2_alu_output_r_2_1_16;
    wire mult2_alu_output_r_2_1_15;
    wire mult2_alu_output_r_2_1_14;
    wire mult2_alu_output_r_2_1_13;
    wire mult2_alu_output_r_2_1_12;
    wire mult2_alu_output_r_2_1_11;
    wire mult2_alu_output_r_2_1_10;
    wire mult2_alu_output_r_2_1_9;
    wire mult2_alu_output_r_2_1_8;
    wire mult2_alu_output_r_2_1_7;
    wire mult2_alu_output_r_2_1_6;
    wire mult2_alu_output_r_2_1_5;
    wire mult2_alu_output_r_2_1_4;
    wire mult2_alu_output_r_2_1_3;
    wire mult2_alu_output_r_2_1_2;
    wire mult2_alu_output_r_2_1_1;
    wire mult2_alu_output_r_2_1_0;
    wire mult2_alu_signedr_1_0;
    wire mult2_alu_output_r_1_0_53;
    wire mult2_alu_output_r_1_0_52;
    wire mult2_alu_output_r_1_0_51;
    wire mult2_alu_output_r_1_0_50;
    wire mult2_alu_output_r_1_0_49;
    wire mult2_alu_output_r_1_0_48;
    wire mult2_alu_output_r_1_0_47;
    wire mult2_alu_output_r_1_0_46;
    wire mult2_alu_output_r_1_0_45;
    wire mult2_alu_output_r_1_0_44;
    wire mult2_alu_output_r_1_0_43;
    wire mult2_alu_output_r_1_0_42;
    wire mult2_alu_output_r_1_0_41;
    wire mult2_alu_output_r_1_0_40;
    wire mult2_alu_output_r_1_0_39;
    wire mult2_alu_output_r_1_0_38;
    wire mult2_alu_output_r_1_0_37;
    wire mult2_alu_output_r_1_0_36;
    wire mult2_alu_output_r_1_0_35;
    wire mult2_alu_output_r_1_0_34;
    wire mult2_alu_output_r_1_0_33;
    wire mult2_alu_output_r_1_0_32;
    wire mult2_alu_output_r_1_0_31;
    wire mult2_alu_output_r_1_0_30;
    wire mult2_alu_output_r_1_0_29;
    wire mult2_alu_output_r_1_0_28;
    wire mult2_alu_output_r_1_0_27;
    wire mult2_alu_output_r_1_0_26;
    wire mult2_alu_output_r_1_0_25;
    wire mult2_alu_output_r_1_0_24;
    wire mult2_alu_output_r_1_0_23;
    wire mult2_alu_output_r_1_0_22;
    wire mult2_alu_output_r_1_0_21;
    wire mult2_alu_output_r_1_0_20;
    wire mult2_alu_output_r_1_0_19;
    wire mult2_alu_output_r_1_0_18;
    wire mult2_alu_output_r_1_0_17;
    wire mult2_alu_output_r_1_0_16;
    wire mult2_alu_output_r_1_0_15;
    wire mult2_alu_output_r_1_0_14;
    wire mult2_alu_output_r_1_0_13;
    wire mult2_alu_output_r_1_0_12;
    wire mult2_alu_output_r_1_0_11;
    wire mult2_alu_output_r_1_0_10;
    wire mult2_alu_output_r_1_0_9;
    wire mult2_alu_output_r_1_0_8;
    wire mult2_alu_output_r_1_0_7;
    wire mult2_alu_output_r_1_0_6;
    wire mult2_alu_output_r_1_0_5;
    wire mult2_alu_output_r_1_0_4;
    wire mult2_alu_output_r_1_0_3;
    wire mult2_alu_output_r_1_0_2;
    wire mult2_alu_output_r_1_0_1;
    wire mult2_alu_output_r_1_0_0;
    wire mult2_0_mult_out_rob_0_17;
    wire mult2_0_mult_out_roa_0_17;
    wire mult2_0_mult_out_rob_0_16;
    wire mult2_0_mult_out_roa_0_16;
    wire mult2_0_mult_out_rob_0_15;
    wire mult2_0_mult_out_roa_0_15;
    wire mult2_0_mult_out_rob_0_14;
    wire mult2_0_mult_out_roa_0_14;
    wire mult2_0_mult_out_rob_0_13;
    wire mult2_0_mult_out_roa_0_13;
    wire mult2_0_mult_out_rob_0_12;
    wire mult2_0_mult_out_roa_0_12;
    wire mult2_0_mult_out_rob_0_11;
    wire mult2_0_mult_out_roa_0_11;
    wire mult2_0_mult_out_rob_0_10;
    wire mult2_0_mult_out_roa_0_10;
    wire mult2_0_mult_out_rob_0_9;
    wire mult2_0_mult_out_roa_0_9;
    wire mult2_0_mult_out_rob_0_8;
    wire mult2_0_mult_out_roa_0_8;
    wire mult2_0_mult_out_rob_0_7;
    wire mult2_0_mult_out_roa_0_7;
    wire mult2_0_mult_out_rob_0_6;
    wire mult2_0_mult_out_roa_0_6;
    wire mult2_0_mult_out_rob_0_5;
    wire mult2_0_mult_out_roa_0_5;
    wire mult2_0_mult_out_rob_0_4;
    wire mult2_0_mult_out_roa_0_4;
    wire mult2_0_mult_out_rob_0_3;
    wire mult2_0_mult_out_roa_0_3;
    wire mult2_0_mult_out_rob_0_2;
    wire mult2_0_mult_out_roa_0_2;
    wire mult2_0_mult_out_rob_0_1;
    wire mult2_0_mult_out_roa_0_1;
    wire mult2_0_mult_out_rob_0_0;
    wire mult2_0_mult_out_roa_0_0;
    wire mult2_0_mult_out_p_0_35;
    wire mult2_0_mult_out_p_0_34;
    wire mult2_0_mult_out_p_0_33;
    wire mult2_0_mult_out_p_0_32;
    wire mult2_0_mult_out_p_0_31;
    wire mult2_0_mult_out_p_0_30;
    wire mult2_0_mult_out_p_0_29;
    wire mult2_0_mult_out_p_0_28;
    wire mult2_0_mult_out_p_0_27;
    wire mult2_0_mult_out_p_0_26;
    wire mult2_0_mult_out_p_0_25;
    wire mult2_0_mult_out_p_0_24;
    wire mult2_0_mult_out_p_0_23;
    wire mult2_0_mult_out_p_0_22;
    wire mult2_0_mult_out_p_0_21;
    wire mult2_0_mult_out_p_0_20;
    wire mult2_0_mult_out_p_0_19;
    wire mult2_0_mult_out_p_0_18;
    wire mult2_0_mult_out_p_0_17;
    wire mult2_0_mult_out_p_0_16;
    wire mult2_0_mult_out_p_0_15;
    wire mult2_0_mult_out_p_0_14;
    wire mult2_0_mult_out_p_0_13;
    wire mult2_0_mult_out_p_0_12;
    wire mult2_0_mult_out_p_0_11;
    wire mult2_0_mult_out_p_0_10;
    wire mult2_0_mult_out_p_0_9;
    wire mult2_0_mult_out_p_0_8;
    wire mult2_0_mult_out_p_0_7;
    wire mult2_0_mult_out_p_0_6;
    wire mult2_0_mult_out_p_0_5;
    wire mult2_0_mult_out_p_0_4;
    wire mult2_0_mult_out_p_0_3;
    wire mult2_0_mult_out_p_0_2;
    wire mult2_0_mult_out_p_0_1;
    wire mult2_0_mult_out_p_0_0;
    wire mult2_0_mult_out_signedp_0;
    wire mult2_0_mult_out_rob_1_17;
    wire mult2_0_mult_out_roa_1_17;
    wire mult2_0_mult_out_rob_1_16;
    wire mult2_0_mult_out_roa_1_16;
    wire mult2_0_mult_out_rob_1_15;
    wire mult2_0_mult_out_roa_1_15;
    wire mult2_0_mult_out_rob_1_14;
    wire mult2_0_mult_out_roa_1_14;
    wire mult2_0_mult_out_rob_1_13;
    wire mult2_0_mult_out_roa_1_13;
    wire mult2_0_mult_out_rob_1_12;
    wire mult2_0_mult_out_roa_1_12;
    wire mult2_0_mult_out_rob_1_11;
    wire mult2_0_mult_out_roa_1_11;
    wire mult2_0_mult_out_rob_1_10;
    wire mult2_0_mult_out_roa_1_10;
    wire mult2_0_mult_out_rob_1_9;
    wire mult2_0_mult_out_roa_1_9;
    wire mult2_0_mult_out_rob_1_8;
    wire mult2_0_mult_out_roa_1_8;
    wire mult2_0_mult_out_rob_1_7;
    wire mult2_0_mult_out_roa_1_7;
    wire mult2_0_mult_out_rob_1_6;
    wire mult2_0_mult_out_roa_1_6;
    wire mult2_0_mult_out_rob_1_5;
    wire mult2_0_mult_out_roa_1_5;
    wire mult2_0_mult_out_rob_1_4;
    wire mult2_0_mult_out_roa_1_4;
    wire mult2_0_mult_out_rob_1_3;
    wire mult2_0_mult_out_roa_1_3;
    wire mult2_0_mult_out_rob_1_2;
    wire mult2_0_mult_out_roa_1_2;
    wire mult2_0_mult_out_rob_1_1;
    wire mult2_0_mult_out_roa_1_1;
    wire mult2_0_mult_out_rob_1_0;
    wire mult2_0_mult_out_roa_1_0;
    wire mult2_0_mult_out_p_1_35;
    wire mult2_0_mult_out_p_1_34;
    wire mult2_0_mult_out_p_1_33;
    wire mult2_0_mult_out_p_1_32;
    wire mult2_0_mult_out_p_1_31;
    wire mult2_0_mult_out_p_1_30;
    wire mult2_0_mult_out_p_1_29;
    wire mult2_0_mult_out_p_1_28;
    wire mult2_0_mult_out_p_1_27;
    wire mult2_0_mult_out_p_1_26;
    wire mult2_0_mult_out_p_1_25;
    wire mult2_0_mult_out_p_1_24;
    wire mult2_0_mult_out_p_1_23;
    wire mult2_0_mult_out_p_1_22;
    wire mult2_0_mult_out_p_1_21;
    wire mult2_0_mult_out_p_1_20;
    wire mult2_0_mult_out_p_1_19;
    wire mult2_0_mult_out_p_1_18;
    wire mult2_0_mult_out_p_1_17;
    wire mult2_0_mult_out_p_1_16;
    wire mult2_0_mult_out_p_1_15;
    wire mult2_0_mult_out_p_1_14;
    wire mult2_0_mult_out_p_1_13;
    wire mult2_0_mult_out_p_1_12;
    wire mult2_0_mult_out_p_1_11;
    wire mult2_0_mult_out_p_1_10;
    wire mult2_0_mult_out_p_1_9;
    wire mult2_0_mult_out_p_1_8;
    wire mult2_0_mult_out_p_1_7;
    wire mult2_0_mult_out_p_1_6;
    wire mult2_0_mult_out_p_1_5;
    wire mult2_0_mult_out_p_1_4;
    wire mult2_0_mult_out_p_1_3;
    wire mult2_0_mult_out_p_1_2;
    wire mult2_0_mult_out_p_1_1;
    wire mult2_0_mult_out_p_1_0;
    wire mult2_0_mult_out_signedp_1;
    wire mult2_0_mult_out_rob_2_17;
    wire mult2_0_mult_out_roa_2_17;
    wire mult2_0_mult_out_rob_2_16;
    wire mult2_0_mult_out_roa_2_16;
    wire mult2_0_mult_out_rob_2_15;
    wire mult2_0_mult_out_roa_2_15;
    wire mult2_0_mult_out_rob_2_14;
    wire mult2_0_mult_out_roa_2_14;
    wire mult2_0_mult_out_rob_2_13;
    wire mult2_0_mult_out_roa_2_13;
    wire mult2_0_mult_out_rob_2_12;
    wire mult2_0_mult_out_roa_2_12;
    wire mult2_0_mult_out_rob_2_11;
    wire mult2_0_mult_out_roa_2_11;
    wire mult2_0_mult_out_rob_2_10;
    wire mult2_0_mult_out_roa_2_10;
    wire mult2_0_mult_out_rob_2_9;
    wire mult2_0_mult_out_roa_2_9;
    wire mult2_0_mult_out_rob_2_8;
    wire mult2_0_mult_out_roa_2_8;
    wire mult2_0_mult_out_rob_2_7;
    wire mult2_0_mult_out_roa_2_7;
    wire mult2_0_mult_out_rob_2_6;
    wire mult2_0_mult_out_roa_2_6;
    wire mult2_0_mult_out_rob_2_5;
    wire mult2_0_mult_out_roa_2_5;
    wire mult2_0_mult_out_rob_2_4;
    wire mult2_0_mult_out_roa_2_4;
    wire mult2_0_mult_out_rob_2_3;
    wire mult2_0_mult_out_roa_2_3;
    wire mult2_0_mult_out_rob_2_2;
    wire mult2_0_mult_out_roa_2_2;
    wire mult2_0_mult_out_rob_2_1;
    wire mult2_0_mult_out_roa_2_1;
    wire mult2_0_mult_out_rob_2_0;
    wire mult2_0_mult_out_roa_2_0;
    wire mult2_0_mult_out_p_2_35;
    wire mult2_0_mult_out_p_2_34;
    wire mult2_0_mult_out_p_2_33;
    wire mult2_0_mult_out_p_2_32;
    wire mult2_0_mult_out_p_2_31;
    wire mult2_0_mult_out_p_2_30;
    wire mult2_0_mult_out_p_2_29;
    wire mult2_0_mult_out_p_2_28;
    wire mult2_0_mult_out_p_2_27;
    wire mult2_0_mult_out_p_2_26;
    wire mult2_0_mult_out_p_2_25;
    wire mult2_0_mult_out_p_2_24;
    wire mult2_0_mult_out_p_2_23;
    wire mult2_0_mult_out_p_2_22;
    wire mult2_0_mult_out_p_2_21;
    wire mult2_0_mult_out_p_2_20;
    wire mult2_0_mult_out_p_2_19;
    wire mult2_0_mult_out_p_2_18;
    wire mult2_0_mult_out_p_2_17;
    wire mult2_0_mult_out_p_2_16;
    wire mult2_0_mult_out_p_2_15;
    wire mult2_0_mult_out_p_2_14;
    wire mult2_0_mult_out_p_2_13;
    wire mult2_0_mult_out_p_2_12;
    wire mult2_0_mult_out_p_2_11;
    wire mult2_0_mult_out_p_2_10;
    wire mult2_0_mult_out_p_2_9;
    wire mult2_0_mult_out_p_2_8;
    wire mult2_0_mult_out_p_2_7;
    wire mult2_0_mult_out_p_2_6;
    wire mult2_0_mult_out_p_2_5;
    wire mult2_0_mult_out_p_2_4;
    wire mult2_0_mult_out_p_2_3;
    wire mult2_0_mult_out_p_2_2;
    wire mult2_0_mult_out_p_2_1;
    wire mult2_0_mult_out_p_2_0;
    wire mult2_0_mult_out_signedp_2;
    wire mdinb3_r_17;
    wire mdinb3_r_16;
    wire mdinb3_r_15;
    wire mdinb3_r_14;
    wire mdinb3_r_13;
    wire mdinb3_r_12;
    wire mdinb3_r_11;
    wire mdinb3_r_10;
    wire mdinb3_r_9;
    wire mdinb3_r_8;
    wire mdinb3_r_7;
    wire mdinb3_r_6;
    wire mdinb3_r_5;
    wire mdinb3_r_4;
    wire mdinb3_r_3;
    wire mdinb3_r_2;
    wire mdinb3_r_1;
    wire mdinb3_r;
    wire mdina3_r_17;
    wire mdina3_r_16;
    wire mdina3_r_15;
    wire mdina3_r_14;
    wire mdina3_r_13;
    wire mdina3_r_12;
    wire mdina3_r_11;
    wire mdina3_r_10;
    wire mdina3_r_9;
    wire mdina3_r_8;
    wire mdina3_r_7;
    wire mdina3_r_6;
    wire mdina3_r_5;
    wire mdina3_r_4;
    wire mdina3_r_3;
    wire mdina3_r_2;
    wire mdina3_r_1;
    wire mdina3_r;
    wire mult2_0_mult_out_rob_3_17;
    wire mult2_0_mult_out_roa_3_17;
    wire mult2_0_mult_out_rob_3_16;
    wire mult2_0_mult_out_roa_3_16;
    wire mult2_0_mult_out_rob_3_15;
    wire mult2_0_mult_out_roa_3_15;
    wire mult2_0_mult_out_rob_3_14;
    wire mult2_0_mult_out_roa_3_14;
    wire mult2_0_mult_out_rob_3_13;
    wire mult2_0_mult_out_roa_3_13;
    wire mult2_0_mult_out_rob_3_12;
    wire mult2_0_mult_out_roa_3_12;
    wire mult2_0_mult_out_rob_3_11;
    wire mult2_0_mult_out_roa_3_11;
    wire mult2_0_mult_out_rob_3_10;
    wire mult2_0_mult_out_roa_3_10;
    wire mult2_0_mult_out_rob_3_9;
    wire mult2_0_mult_out_roa_3_9;
    wire mult2_0_mult_out_rob_3_8;
    wire mult2_0_mult_out_roa_3_8;
    wire mult2_0_mult_out_rob_3_7;
    wire mult2_0_mult_out_roa_3_7;
    wire mult2_0_mult_out_rob_3_6;
    wire mult2_0_mult_out_roa_3_6;
    wire mult2_0_mult_out_rob_3_5;
    wire mult2_0_mult_out_roa_3_5;
    wire mult2_0_mult_out_rob_3_4;
    wire mult2_0_mult_out_roa_3_4;
    wire mult2_0_mult_out_rob_3_3;
    wire mult2_0_mult_out_roa_3_3;
    wire mult2_0_mult_out_rob_3_2;
    wire mult2_0_mult_out_roa_3_2;
    wire mult2_0_mult_out_rob_3_1;
    wire mult2_0_mult_out_roa_3_1;
    wire mult2_0_mult_out_rob_3_0;
    wire mult2_0_mult_out_roa_3_0;
    wire mult2_0_mult_out_p_3_35;
    wire mult2_0_mult_out_p_3_34;
    wire mult2_0_mult_out_p_3_33;
    wire mult2_0_mult_out_p_3_32;
    wire mult2_0_mult_out_p_3_31;
    wire mult2_0_mult_out_p_3_30;
    wire mult2_0_mult_out_p_3_29;
    wire mult2_0_mult_out_p_3_28;
    wire mult2_0_mult_out_p_3_27;
    wire mult2_0_mult_out_p_3_26;
    wire mult2_0_mult_out_p_3_25;
    wire mult2_0_mult_out_p_3_24;
    wire mult2_0_mult_out_p_3_23;
    wire mult2_0_mult_out_p_3_22;
    wire mult2_0_mult_out_p_3_21;
    wire mult2_0_mult_out_p_3_20;
    wire mult2_0_mult_out_p_3_19;
    wire mult2_0_mult_out_p_3_18;
    wire mult2_0_mult_out_p_3_17;
    wire mult2_0_mult_out_p_3_16;
    wire mult2_0_mult_out_p_3_15;
    wire mult2_0_mult_out_p_3_14;
    wire mult2_0_mult_out_p_3_13;
    wire mult2_0_mult_out_p_3_12;
    wire mult2_0_mult_out_p_3_11;
    wire mult2_0_mult_out_p_3_10;
    wire mult2_0_mult_out_p_3_9;
    wire mult2_0_mult_out_p_3_8;
    wire mult2_0_mult_out_p_3_7;
    wire mult2_0_mult_out_p_3_6;
    wire mult2_0_mult_out_p_3_5;
    wire mult2_0_mult_out_p_3_4;
    wire mult2_0_mult_out_p_3_3;
    wire mult2_0_mult_out_p_3_2;
    wire mult2_0_mult_out_p_3_1;
    wire mult2_0_mult_out_p_3_0;
    wire mult2_0_mult_out_signedp_3;
    wire mult_shift_out_b_4_1_1_17;
    wire mult_shift_out_b_4_1_1_16;
    wire mult_shift_out_b_4_1_1_15;
    wire mult_shift_out_b_4_1_1_14;
    wire mult_shift_out_b_4_1_1_13;
    wire mult_shift_out_b_4_1_1_12;
    wire mult_shift_out_b_4_1_1_11;
    wire mult_shift_out_b_4_1_1_10;
    wire mult_shift_out_b_4_1_1_9;
    wire mult_shift_out_b_4_1_1_8;
    wire mult_shift_out_b_4_1_1_7;
    wire mult_shift_out_b_4_1_1_6;
    wire mult_shift_out_b_4_1_1_5;
    wire mult_shift_out_b_4_1_1_4;
    wire mult_shift_out_b_4_1_1_3;
    wire mult_shift_out_b_4_1_1_2;
    wire mult_shift_out_b_4_1_1_1;
    wire mult_shift_out_b_4_1_1_0;
    wire mdinb4_r_17;
    wire mdinb4_r_16;
    wire mdinb4_r_15;
    wire mdinb4_r_14;
    wire mdinb4_r_13;
    wire mdinb4_r_12;
    wire mdinb4_r_11;
    wire mdinb4_r_10;
    wire mdinb4_r_9;
    wire mdinb4_r_8;
    wire mdinb4_r_7;
    wire mdinb4_r_6;
    wire mdinb4_r_5;
    wire mdinb4_r_4;
    wire mdinb4_r_3;
    wire mdinb4_r_2;
    wire mdinb4_r_1;
    wire mdinb4_r;
    wire mdina4_r_17;
    wire mdina4_r_16;
    wire mdina4_r_15;
    wire mdina4_r_14;
    wire mdina4_r_13;
    wire mdina4_r_12;
    wire mdina4_r_11;
    wire mdina4_r_10;
    wire mdina4_r_9;
    wire mdina4_r_8;
    wire mdina4_r_7;
    wire mdina4_r_6;
    wire mdina4_r_5;
    wire mdina4_r_4;
    wire mdina4_r_3;
    wire mdina4_r_2;
    wire mdina4_r_1;
    wire mdina4_r;

    FD1P3DX FF_89 (.D(A[0]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina3_r))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_88 (.D(A[1]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina3_r_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_87 (.D(A[2]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina3_r_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_86 (.D(A[3]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina3_r_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_85 (.D(A[4]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina3_r_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_84 (.D(A[5]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina3_r_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_83 (.D(A[6]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina3_r_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_82 (.D(A[7]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina3_r_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_81 (.D(A[8]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina3_r_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_80 (.D(A[9]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina3_r_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_79 (.D(A[10]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina3_r_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_78 (.D(A[11]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina3_r_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_77 (.D(A[12]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina3_r_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_76 (.D(A[13]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina3_r_13))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_75 (.D(A[14]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina3_r_14))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_74 (.D(A[15]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina3_r_15))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_73 (.D(A[16]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina3_r_16))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_72 (.D(A[17]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina3_r_17))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_71 (.D(B[18]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb3_r))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_70 (.D(B[19]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb3_r_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_69 (.D(B[20]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb3_r_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_68 (.D(B[21]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb3_r_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_67 (.D(B[22]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb3_r_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_66 (.D(B[23]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb3_r_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_65 (.D(B[24]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb3_r_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_64 (.D(B[25]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb3_r_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_63 (.D(B[26]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb3_r_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_62 (.D(B[27]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb3_r_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_61 (.D(B[28]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb3_r_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_60 (.D(B[29]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb3_r_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_59 (.D(B[30]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb3_r_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_58 (.D(B[31]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb3_r_13))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_57 (.D(B[32]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb3_r_14))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_56 (.D(B[33]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb3_r_15))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_55 (.D(B[34]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb3_r_16))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_54 (.D(B[35]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb3_r_17))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_53 (.D(A[18]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina4_r))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_52 (.D(A[19]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina4_r_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_51 (.D(A[20]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina4_r_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_50 (.D(A[21]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina4_r_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_49 (.D(A[22]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina4_r_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_48 (.D(A[23]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina4_r_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_47 (.D(A[24]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina4_r_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_46 (.D(A[25]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina4_r_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_45 (.D(A[26]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina4_r_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_44 (.D(A[27]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina4_r_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_43 (.D(A[28]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina4_r_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_42 (.D(A[29]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina4_r_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_41 (.D(A[30]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina4_r_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_40 (.D(A[31]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina4_r_13))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_39 (.D(A[32]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina4_r_14))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_38 (.D(A[33]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina4_r_15))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_37 (.D(A[34]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina4_r_16))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_36 (.D(A[35]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdina4_r_17))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_35 (.D(B[18]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb4_r))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_34 (.D(B[19]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb4_r_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_33 (.D(B[20]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb4_r_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_32 (.D(B[21]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb4_r_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_31 (.D(B[22]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb4_r_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_30 (.D(B[23]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb4_r_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_29 (.D(B[24]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb4_r_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_28 (.D(B[25]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb4_r_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_27 (.D(B[26]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb4_r_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_26 (.D(B[27]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb4_r_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_25 (.D(B[28]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb4_r_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_24 (.D(B[29]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb4_r_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_23 (.D(B[30]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb4_r_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_22 (.D(B[31]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb4_r_13))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_21 (.D(B[32]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb4_r_14))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_20 (.D(B[33]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb4_r_15))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_19 (.D(B[34]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb4_r_16))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_18 (.D(B[35]), .SP(CE0), .CK(CLK0), .CD(RST0), .Q(mdinb4_r_17))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_17 (.D(mult2_alu_output_r_1_0_0), .SP(CE0), .CK(CLK0), .CD(RST0),
        .Q(P[0]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_16 (.D(mult2_alu_output_r_1_0_1), .SP(CE0), .CK(CLK0), .CD(RST0),
        .Q(P[1]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_15 (.D(mult2_alu_output_r_1_0_2), .SP(CE0), .CK(CLK0), .CD(RST0),
        .Q(P[2]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_14 (.D(mult2_alu_output_r_1_0_3), .SP(CE0), .CK(CLK0), .CD(RST0),
        .Q(P[3]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_13 (.D(mult2_alu_output_r_1_0_4), .SP(CE0), .CK(CLK0), .CD(RST0),
        .Q(P[4]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_12 (.D(mult2_alu_output_r_1_0_5), .SP(CE0), .CK(CLK0), .CD(RST0),
        .Q(P[5]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_11 (.D(mult2_alu_output_r_1_0_6), .SP(CE0), .CK(CLK0), .CD(RST0),
        .Q(P[6]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_10 (.D(mult2_alu_output_r_1_0_7), .SP(CE0), .CK(CLK0), .CD(RST0),
        .Q(P[7]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_9 (.D(mult2_alu_output_r_1_0_8), .SP(CE0), .CK(CLK0), .CD(RST0),
        .Q(P[8]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_8 (.D(mult2_alu_output_r_1_0_9), .SP(CE0), .CK(CLK0), .CD(RST0),
        .Q(P[9]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_7 (.D(mult2_alu_output_r_1_0_10), .SP(CE0), .CK(CLK0), .CD(RST0),
        .Q(P[10]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_6 (.D(mult2_alu_output_r_1_0_11), .SP(CE0), .CK(CLK0), .CD(RST0),
        .Q(P[11]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_5 (.D(mult2_alu_output_r_1_0_12), .SP(CE0), .CK(CLK0), .CD(RST0),
        .Q(P[12]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_4 (.D(mult2_alu_output_r_1_0_13), .SP(CE0), .CK(CLK0), .CD(RST0),
        .Q(P[13]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_3 (.D(mult2_alu_output_r_1_0_14), .SP(CE0), .CK(CLK0), .CD(RST0),
        .Q(P[14]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_2 (.D(mult2_alu_output_r_1_0_15), .SP(CE0), .CK(CLK0), .CD(RST0),
        .Q(P[15]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_1 (.D(mult2_alu_output_r_1_0_16), .SP(CE0), .CK(CLK0), .CD(RST0),
        .Q(P[16]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_0 (.D(mult2_alu_output_r_1_0_17), .SP(CE0), .CK(CLK0), .CD(RST0),
        .Q(P[17]))
             /* synthesis GSR="ENABLED" */;

    defparam dsp_alu_1.CLK3_DIV = "ENABLED" ;
    defparam dsp_alu_1.CLK2_DIV = "ENABLED" ;
    defparam dsp_alu_1.CLK1_DIV = "ENABLED" ;
    defparam dsp_alu_1.CLK0_DIV = "ENABLED" ;
    // defparam dsp_alu_1.REG_INPUTCFB_RST = "RST0" ;
    // defparam dsp_alu_1.REG_INPUTCFB_CE = "CE0" ;
    // defparam dsp_alu_1.REG_INPUTCFB_CLK = "NONE" ;
    defparam dsp_alu_1.REG_OPCODEIN_1_RST = "RST0" ;
    defparam dsp_alu_1.REG_OPCODEIN_1_CE = "CE0" ;
    defparam dsp_alu_1.REG_OPCODEIN_1_CLK = "NONE" ;
    defparam dsp_alu_1.REG_OPCODEIN_0_RST = "RST0" ;
    defparam dsp_alu_1.REG_OPCODEIN_0_CE = "CE0" ;
    defparam dsp_alu_1.REG_OPCODEIN_0_CLK = "NONE" ;
    // defparam dsp_alu_1.REG_OPCODEOP1_1_CLK = "NONE" ;
    defparam dsp_alu_1.REG_OPCODEOP1_0_CLK = "NONE" ;
    defparam dsp_alu_1.REG_OPCODEOP0_1_RST = "RST0" ;
    defparam dsp_alu_1.REG_OPCODEOP0_1_CE = "CE0" ;
    defparam dsp_alu_1.REG_OPCODEOP0_1_CLK = "NONE" ;
    defparam dsp_alu_1.REG_OPCODEOP0_0_RST = "RST0" ;
    defparam dsp_alu_1.REG_OPCODEOP0_0_CE = "CE0" ;
    defparam dsp_alu_1.REG_OPCODEOP0_0_CLK = "NONE" ;
    // defparam dsp_alu_1.REG_INPUTC1_RST = "RST0" ;
    // defparam dsp_alu_1.REG_INPUTC1_CE = "CE0" ;
    defparam dsp_alu_1.REG_INPUTC1_CLK = "NONE" ;
    // defparam dsp_alu_1.REG_INPUTC0_RST = "RST0" ;
    // defparam dsp_alu_1.REG_INPUTC0_CE = "CE0" ;
    defparam dsp_alu_1.REG_INPUTC0_CLK = "NONE" ;
    defparam dsp_alu_1.LEGACY = "DISABLED" ;
    // defparam dsp_alu_1.REG_FLAG_RST = "RST0" ;
    // defparam dsp_alu_1.REG_FLAG_CE = "CE0" ;
    defparam dsp_alu_1.REG_FLAG_CLK = "NONE" ;
    // defparam dsp_alu_1.REG_OUTPUT1_RST = "RST0" ;
    // defparam dsp_alu_1.REG_OUTPUT1_CE = "CE0" ;
    defparam dsp_alu_1.REG_OUTPUT1_CLK = "CLK0" ;
    // defparam dsp_alu_1.REG_OUTPUT0_RST = "RST0" ;
    // defparam dsp_alu_1.REG_OUTPUT0_CE = "CE0" ;
    defparam dsp_alu_1.REG_OUTPUT0_CLK = "CLK0" ;
    // defparam dsp_alu_1.MULT9_MODE = "DISABLED" ;
    defparam dsp_alu_1.RNDPAT = "0x00000000000000" ;
    defparam dsp_alu_1.MASKPAT = "0x00000000000000" ;
    defparam dsp_alu_1.MCPAT = "0x00000000000000" ;
    defparam dsp_alu_1.MASK01 = "0x00000000000000" ;
    defparam dsp_alu_1.MASKPAT_SOURCE = "STATIC" ;
    defparam dsp_alu_1.MCPAT_SOURCE = "STATIC" ;
    defparam dsp_alu_1.RESETMODE = "SYNC" ;
    defparam dsp_alu_1.GSR = "ENABLED" ;
    ALU54B dsp_alu_1 (.A35(mult2_0_mult_out_rob_0_17), .A34(mult2_0_mult_out_rob_0_16),
        .A33(mult2_0_mult_out_rob_0_15), .A32(mult2_0_mult_out_rob_0_14),
        .A31(mult2_0_mult_out_rob_0_13), .A30(mult2_0_mult_out_rob_0_12),
        .A29(mult2_0_mult_out_rob_0_11), .A28(mult2_0_mult_out_rob_0_10),
        .A27(mult2_0_mult_out_rob_0_9), .A26(mult2_0_mult_out_rob_0_8),
        .A25(mult2_0_mult_out_rob_0_7), .A24(mult2_0_mult_out_rob_0_6),
        .A23(mult2_0_mult_out_rob_0_5), .A22(mult2_0_mult_out_rob_0_4),
        .A21(mult2_0_mult_out_rob_0_3), .A20(mult2_0_mult_out_rob_0_2),
        .A19(mult2_0_mult_out_rob_0_1), .A18(mult2_0_mult_out_rob_0_0),
        .A17(mult2_0_mult_out_roa_0_17), .A16(mult2_0_mult_out_roa_0_16),
        .A15(mult2_0_mult_out_roa_0_15), .A14(mult2_0_mult_out_roa_0_14),
        .A13(mult2_0_mult_out_roa_0_13), .A12(mult2_0_mult_out_roa_0_12),
        .A11(mult2_0_mult_out_roa_0_11), .A10(mult2_0_mult_out_roa_0_10),
        .A9(mult2_0_mult_out_roa_0_9), .A8(mult2_0_mult_out_roa_0_8), .A7(mult2_0_mult_out_roa_0_7),
        .A6(mult2_0_mult_out_roa_0_6), .A5(mult2_0_mult_out_roa_0_5), .A4(mult2_0_mult_out_roa_0_4),
        .A3(mult2_0_mult_out_roa_0_3), .A2(mult2_0_mult_out_roa_0_2), .A1(mult2_0_mult_out_roa_0_1),
        .A0(mult2_0_mult_out_roa_0_0), .B35(mult2_0_mult_out_rob_1_17),
        .B34(mult2_0_mult_out_rob_1_16), .B33(mult2_0_mult_out_rob_1_15),
        .B32(mult2_0_mult_out_rob_1_14), .B31(mult2_0_mult_out_rob_1_13),
        .B30(mult2_0_mult_out_rob_1_12), .B29(mult2_0_mult_out_rob_1_11),
        .B28(mult2_0_mult_out_rob_1_10), .B27(mult2_0_mult_out_rob_1_9),
        .B26(mult2_0_mult_out_rob_1_8), .B25(mult2_0_mult_out_rob_1_7),
        .B24(mult2_0_mult_out_rob_1_6), .B23(mult2_0_mult_out_rob_1_5),
        .B22(mult2_0_mult_out_rob_1_4), .B21(mult2_0_mult_out_rob_1_3),
        .B20(mult2_0_mult_out_rob_1_2), .B19(mult2_0_mult_out_rob_1_1),
        .B18(mult2_0_mult_out_rob_1_0), .B17(mult2_0_mult_out_roa_1_17),
        .B16(mult2_0_mult_out_roa_1_16), .B15(mult2_0_mult_out_roa_1_15),
        .B14(mult2_0_mult_out_roa_1_14), .B13(mult2_0_mult_out_roa_1_13),
        .B12(mult2_0_mult_out_roa_1_12), .B11(mult2_0_mult_out_roa_1_11),
        .B10(mult2_0_mult_out_roa_1_10), .B9(mult2_0_mult_out_roa_1_9),
        .B8(mult2_0_mult_out_roa_1_8), .B7(mult2_0_mult_out_roa_1_7), .B6(mult2_0_mult_out_roa_1_6),
        .B5(mult2_0_mult_out_roa_1_5), .B4(mult2_0_mult_out_roa_1_4), .B3(mult2_0_mult_out_roa_1_3),
        .B2(mult2_0_mult_out_roa_1_2), .B1(mult2_0_mult_out_roa_1_1), .B0(mult2_0_mult_out_roa_1_0),
        .CFB53(1'b0), .CFB52(1'b0), .CFB51(1'b0), .CFB50(1'b0),
        .CFB49(1'b0), .CFB48(1'b0), .CFB47(1'b0), .CFB46(1'b0),
        .CFB45(1'b0), .CFB44(1'b0), .CFB43(1'b0), .CFB42(1'b0),
        .CFB41(1'b0), .CFB40(1'b0), .CFB39(1'b0), .CFB38(1'b0),
        .CFB37(1'b0), .CFB36(1'b0), .CFB35(1'b0), .CFB34(1'b0),
        .CFB33(1'b0), .CFB32(1'b0), .CFB31(1'b0), .CFB30(1'b0),
        .CFB29(1'b0), .CFB28(1'b0), .CFB27(1'b0), .CFB26(1'b0),
        .CFB25(1'b0), .CFB24(1'b0), .CFB23(1'b0), .CFB22(1'b0),
        .CFB21(1'b0), .CFB20(1'b0), .CFB19(1'b0), .CFB18(1'b0),
        .CFB17(1'b0), .CFB16(1'b0), .CFB15(1'b0), .CFB14(1'b0),
        .CFB13(1'b0), .CFB12(1'b0), .CFB11(1'b0), .CFB10(1'b0),
        .CFB9(1'b0), .CFB8(1'b0), .CFB7(1'b0), .CFB6(1'b0),
        .CFB5(1'b0), .CFB4(1'b0), .CFB3(1'b0), .CFB2(1'b0),
        .CFB1(1'b0), .CFB0(1'b0), .C53(1'b0), .C52(1'b0),
        .C51(1'b0), .C50(1'b0), .C49(1'b0), .C48(1'b0),
        .C47(1'b0), .C46(1'b0), .C45(1'b0), .C44(1'b0),
        .C43(1'b0), .C42(1'b0), .C41(1'b0), .C40(1'b0),
        .C39(1'b0), .C38(1'b0), .C37(1'b0), .C36(1'b0),
        .C35(1'b0), .C34(1'b0), .C33(1'b0), .C32(1'b0),
        .C31(1'b0), .C30(1'b0), .C29(1'b0), .C28(1'b0),
        .C27(1'b0), .C26(1'b0), .C25(1'b0), .C24(1'b0),
        .C23(1'b0), .C22(1'b0), .C21(1'b0), .C20(1'b0),
        .C19(1'b0), .C18(1'b0), .C17(1'b0), .C16(1'b0),
        .C15(1'b0), .C14(1'b0), .C13(1'b0), .C12(1'b0),
        .C11(1'b0), .C10(1'b0), .C9(1'b0), .C8(1'b0),
        .C7(1'b0), .C6(1'b0), .C5(1'b0), .C4(1'b0),
        .C3(1'b0), .C2(1'b0), .C1(1'b0), .C0(1'b0),
        .CE0(CE0), .CE1(1'b1), .CE2(1'b1), .CE3(1'b1), .CLK0(CLK0),
        .CLK1(CLK0), .CLK2(1'b0), .CLK3(1'b0), .RST0(RST0), .RST1(1'b0),
        .RST2(1'b0), .RST3(1'b0), .SIGNEDIA(mult2_0_mult_out_signedp_0),
        .SIGNEDIB(mult2_0_mult_out_signedp_1), .SIGNEDCIN(mult2_alu_signedcin_1_0),
        .MA35(mult2_0_mult_out_p_0_35), .MA34(mult2_0_mult_out_p_0_34),
        .MA33(mult2_0_mult_out_p_0_33), .MA32(mult2_0_mult_out_p_0_32),
        .MA31(mult2_0_mult_out_p_0_31), .MA30(mult2_0_mult_out_p_0_30),
        .MA29(mult2_0_mult_out_p_0_29), .MA28(mult2_0_mult_out_p_0_28),
        .MA27(mult2_0_mult_out_p_0_27), .MA26(mult2_0_mult_out_p_0_26),
        .MA25(mult2_0_mult_out_p_0_25), .MA24(mult2_0_mult_out_p_0_24),
        .MA23(mult2_0_mult_out_p_0_23), .MA22(mult2_0_mult_out_p_0_22),
        .MA21(mult2_0_mult_out_p_0_21), .MA20(mult2_0_mult_out_p_0_20),
        .MA19(mult2_0_mult_out_p_0_19), .MA18(mult2_0_mult_out_p_0_18),
        .MA17(mult2_0_mult_out_p_0_17), .MA16(mult2_0_mult_out_p_0_16),
        .MA15(mult2_0_mult_out_p_0_15), .MA14(mult2_0_mult_out_p_0_14),
        .MA13(mult2_0_mult_out_p_0_13), .MA12(mult2_0_mult_out_p_0_12),
        .MA11(mult2_0_mult_out_p_0_11), .MA10(mult2_0_mult_out_p_0_10),
        .MA9(mult2_0_mult_out_p_0_9), .MA8(mult2_0_mult_out_p_0_8), .MA7(mult2_0_mult_out_p_0_7),
        .MA6(mult2_0_mult_out_p_0_6), .MA5(mult2_0_mult_out_p_0_5), .MA4(mult2_0_mult_out_p_0_4),
        .MA3(mult2_0_mult_out_p_0_3), .MA2(mult2_0_mult_out_p_0_2), .MA1(mult2_0_mult_out_p_0_1),
        .MA0(mult2_0_mult_out_p_0_0), .MB35(mult2_0_mult_out_p_1_35), .MB34(mult2_0_mult_out_p_1_34),
        .MB33(mult2_0_mult_out_p_1_33), .MB32(mult2_0_mult_out_p_1_32),
        .MB31(mult2_0_mult_out_p_1_31), .MB30(mult2_0_mult_out_p_1_30),
        .MB29(mult2_0_mult_out_p_1_29), .MB28(mult2_0_mult_out_p_1_28),
        .MB27(mult2_0_mult_out_p_1_27), .MB26(mult2_0_mult_out_p_1_26),
        .MB25(mult2_0_mult_out_p_1_25), .MB24(mult2_0_mult_out_p_1_24),
        .MB23(mult2_0_mult_out_p_1_23), .MB22(mult2_0_mult_out_p_1_22),
        .MB21(mult2_0_mult_out_p_1_21), .MB20(mult2_0_mult_out_p_1_20),
        .MB19(mult2_0_mult_out_p_1_19), .MB18(mult2_0_mult_out_p_1_18),
        .MB17(mult2_0_mult_out_p_1_17), .MB16(mult2_0_mult_out_p_1_16),
        .MB15(mult2_0_mult_out_p_1_15), .MB14(mult2_0_mult_out_p_1_14),
        .MB13(mult2_0_mult_out_p_1_13), .MB12(mult2_0_mult_out_p_1_12),
        .MB11(mult2_0_mult_out_p_1_11), .MB10(mult2_0_mult_out_p_1_10),
        .MB9(mult2_0_mult_out_p_1_9), .MB8(mult2_0_mult_out_p_1_8), .MB7(mult2_0_mult_out_p_1_7),
        .MB6(mult2_0_mult_out_p_1_6), .MB5(mult2_0_mult_out_p_1_5), .MB4(mult2_0_mult_out_p_1_4),
        .MB3(mult2_0_mult_out_p_1_3), .MB2(mult2_0_mult_out_p_1_2), .MB1(mult2_0_mult_out_p_1_1),
        .MB0(mult2_0_mult_out_p_1_0), .CIN53(mult2_alu_in_cin_1_0_53), .CIN52(mult2_alu_in_cin_1_0_52),
        .CIN51(mult2_alu_in_cin_1_0_51), .CIN50(mult2_alu_in_cin_1_0_50),
        .CIN49(mult2_alu_in_cin_1_0_49), .CIN48(mult2_alu_in_cin_1_0_48),
        .CIN47(mult2_alu_in_cin_1_0_47), .CIN46(mult2_alu_in_cin_1_0_46),
        .CIN45(mult2_alu_in_cin_1_0_45), .CIN44(mult2_alu_in_cin_1_0_44),
        .CIN43(mult2_alu_in_cin_1_0_43), .CIN42(mult2_alu_in_cin_1_0_42),
        .CIN41(mult2_alu_in_cin_1_0_41), .CIN40(mult2_alu_in_cin_1_0_40),
        .CIN39(mult2_alu_in_cin_1_0_39), .CIN38(mult2_alu_in_cin_1_0_38),
        .CIN37(mult2_alu_in_cin_1_0_37), .CIN36(mult2_alu_in_cin_1_0_36),
        .CIN35(mult2_alu_in_cin_1_0_35), .CIN34(mult2_alu_in_cin_1_0_34),
        .CIN33(mult2_alu_in_cin_1_0_33), .CIN32(mult2_alu_in_cin_1_0_32),
        .CIN31(mult2_alu_in_cin_1_0_31), .CIN30(mult2_alu_in_cin_1_0_30),
        .CIN29(mult2_alu_in_cin_1_0_29), .CIN28(mult2_alu_in_cin_1_0_28),
        .CIN27(mult2_alu_in_cin_1_0_27), .CIN26(mult2_alu_in_cin_1_0_26),
        .CIN25(mult2_alu_in_cin_1_0_25), .CIN24(mult2_alu_in_cin_1_0_24),
        .CIN23(mult2_alu_in_cin_1_0_23), .CIN22(mult2_alu_in_cin_1_0_22),
        .CIN21(mult2_alu_in_cin_1_0_21), .CIN20(mult2_alu_in_cin_1_0_20),
        .CIN19(mult2_alu_in_cin_1_0_19), .CIN18(mult2_alu_in_cin_1_0_18),
        .CIN17(mult2_alu_in_cin_1_0_17), .CIN16(mult2_alu_in_cin_1_0_16),
        .CIN15(mult2_alu_in_cin_1_0_15), .CIN14(mult2_alu_in_cin_1_0_14),
        .CIN13(mult2_alu_in_cin_1_0_13), .CIN12(mult2_alu_in_cin_1_0_12),
        .CIN11(mult2_alu_in_cin_1_0_11), .CIN10(mult2_alu_in_cin_1_0_10),
        .CIN9(mult2_alu_in_cin_1_0_9), .CIN8(mult2_alu_in_cin_1_0_8), .CIN7(mult2_alu_in_cin_1_0_7),
        .CIN6(mult2_alu_in_cin_1_0_6), .CIN5(mult2_alu_in_cin_1_0_5), .CIN4(mult2_alu_in_cin_1_0_4),
        .CIN3(mult2_alu_in_cin_1_0_3), .CIN2(mult2_alu_in_cin_1_0_2), .CIN1(mult2_alu_in_cin_1_0_1),
        .CIN0(mult2_alu_in_cin_1_0_0), .OP10(1'b0), .OP9(1'b1),
        .OP8(1'b0), .OP7(1'b0), .OP6(1'b0), .OP5(1'b0),
        .OP4(1'b0), .OP3(1'b0), .OP2(1'b0), .OP1(1'b0),
        .OP0(1'b1), .R53(mult2_alu_output_r_1_0_53), .R52(mult2_alu_output_r_1_0_52),
        .R51(mult2_alu_output_r_1_0_51), .R50(mult2_alu_output_r_1_0_50),
        .R49(mult2_alu_output_r_1_0_49), .R48(mult2_alu_output_r_1_0_48),
        .R47(mult2_alu_output_r_1_0_47), .R46(mult2_alu_output_r_1_0_46),
        .R45(mult2_alu_output_r_1_0_45), .R44(mult2_alu_output_r_1_0_44),
        .R43(mult2_alu_output_r_1_0_43), .R42(mult2_alu_output_r_1_0_42),
        .R41(mult2_alu_output_r_1_0_41), .R40(mult2_alu_output_r_1_0_40),
        .R39(mult2_alu_output_r_1_0_39), .R38(mult2_alu_output_r_1_0_38),
        .R37(mult2_alu_output_r_1_0_37), .R36(mult2_alu_output_r_1_0_36),
        .R35(mult2_alu_output_r_1_0_35), .R34(mult2_alu_output_r_1_0_34),
        .R33(mult2_alu_output_r_1_0_33), .R32(mult2_alu_output_r_1_0_32),
        .R31(mult2_alu_output_r_1_0_31), .R30(mult2_alu_output_r_1_0_30),
        .R29(mult2_alu_output_r_1_0_29), .R28(mult2_alu_output_r_1_0_28),
        .R27(mult2_alu_output_r_1_0_27), .R26(mult2_alu_output_r_1_0_26),
        .R25(mult2_alu_output_r_1_0_25), .R24(mult2_alu_output_r_1_0_24),
        .R23(mult2_alu_output_r_1_0_23), .R22(mult2_alu_output_r_1_0_22),
        .R21(mult2_alu_output_r_1_0_21), .R20(mult2_alu_output_r_1_0_20),
        .R19(mult2_alu_output_r_1_0_19), .R18(mult2_alu_output_r_1_0_18),
        .R17(mult2_alu_output_r_1_0_17), .R16(mult2_alu_output_r_1_0_16),
        .R15(mult2_alu_output_r_1_0_15), .R14(mult2_alu_output_r_1_0_14),
        .R13(mult2_alu_output_r_1_0_13), .R12(mult2_alu_output_r_1_0_12),
        .R11(mult2_alu_output_r_1_0_11), .R10(mult2_alu_output_r_1_0_10),
        .R9(mult2_alu_output_r_1_0_9), .R8(mult2_alu_output_r_1_0_8), .R7(mult2_alu_output_r_1_0_7),
        .R6(mult2_alu_output_r_1_0_6), .R5(mult2_alu_output_r_1_0_5), .R4(mult2_alu_output_r_1_0_4),
        .R3(mult2_alu_output_r_1_0_3), .R2(mult2_alu_output_r_1_0_2), .R1(mult2_alu_output_r_1_0_1),
        .R0(mult2_alu_output_r_1_0_0), .CO53(), .CO52(), .CO51(), .CO50(),
        .CO49(), .CO48(), .CO47(), .CO46(), .CO45(), .CO44(), .CO43(), .CO42(),
        .CO41(), .CO40(), .CO39(), .CO38(), .CO37(), .CO36(), .CO35(), .CO34(),
        .CO33(), .CO32(), .CO31(), .CO30(), .CO29(), .CO28(), .CO27(), .CO26(),
        .CO25(), .CO24(), .CO23(), .CO22(), .CO21(), .CO20(), .CO19(), .CO18(),
        .CO17(), .CO16(), .CO15(), .CO14(), .CO13(), .CO12(), .CO11(), .CO10(),
        .CO9(), .CO8(), .CO7(), .CO6(), .CO5(), .CO4(), .CO3(), .CO2(),
        .CO1(), .CO0(), .EQZ(), .EQZM(), .EQOM(), .EQPAT(), .EQPATB(), .OVER(),
        .UNDER(), .OVERUNDER(), .SIGNEDR(mult2_alu_signedr_1_0));

    defparam dsp_alu_0.CLK3_DIV = "ENABLED" ;
    defparam dsp_alu_0.CLK2_DIV = "ENABLED" ;
    defparam dsp_alu_0.CLK1_DIV = "ENABLED" ;
    defparam dsp_alu_0.CLK0_DIV = "ENABLED" ;
    // defparam dsp_alu_0.REG_INPUTCFB_RST = "RST0" ;
    // defparam dsp_alu_0.REG_INPUTCFB_CE = "CE0" ;
    // defparam dsp_alu_0.REG_INPUTCFB_CLK = "NONE" ;
    defparam dsp_alu_0.REG_OPCODEIN_1_RST = "RST0" ;
    defparam dsp_alu_0.REG_OPCODEIN_1_CE = "CE0" ;
    defparam dsp_alu_0.REG_OPCODEIN_1_CLK = "NONE" ;
    defparam dsp_alu_0.REG_OPCODEIN_0_RST = "RST0" ;
    defparam dsp_alu_0.REG_OPCODEIN_0_CE = "CE0" ;
    defparam dsp_alu_0.REG_OPCODEIN_0_CLK = "NONE" ;
    // defparam dsp_alu_0.REG_OPCODEOP1_1_CLK = "NONE" ;
    defparam dsp_alu_0.REG_OPCODEOP1_0_CLK = "NONE" ;
    defparam dsp_alu_0.REG_OPCODEOP0_1_RST = "RST0" ;
    defparam dsp_alu_0.REG_OPCODEOP0_1_CE = "CE0" ;
    defparam dsp_alu_0.REG_OPCODEOP0_1_CLK = "NONE" ;
    defparam dsp_alu_0.REG_OPCODEOP0_0_RST = "RST0" ;
    defparam dsp_alu_0.REG_OPCODEOP0_0_CE = "CE0" ;
    defparam dsp_alu_0.REG_OPCODEOP0_0_CLK = "NONE" ;
    // defparam dsp_alu_0.REG_INPUTC1_RST = "RST0" ;
    // defparam dsp_alu_0.REG_INPUTC1_CE = "CE0" ;
    defparam dsp_alu_0.REG_INPUTC1_CLK = "NONE" ;
    // defparam dsp_alu_0.REG_INPUTC0_RST = "RST0" ;
    // defparam dsp_alu_0.REG_INPUTC0_CE = "CE0" ;
    defparam dsp_alu_0.REG_INPUTC0_CLK = "NONE" ;
    defparam dsp_alu_0.LEGACY = "DISABLED" ;
    // defparam dsp_alu_0.REG_FLAG_RST = "RST0" ;
    // defparam dsp_alu_0.REG_FLAG_CE = "CE0" ;
    defparam dsp_alu_0.REG_FLAG_CLK = "NONE" ;
    // defparam dsp_alu_0.REG_OUTPUT1_RST = "RST0" ;
    // defparam dsp_alu_0.REG_OUTPUT1_CE = "CE0" ;
    defparam dsp_alu_0.REG_OUTPUT1_CLK = "CLK0" ;
    // defparam dsp_alu_0.REG_OUTPUT0_RST = "RST0" ;
    // defparam dsp_alu_0.REG_OUTPUT0_CE = "CE0" ;
    defparam dsp_alu_0.REG_OUTPUT0_CLK = "CLK0" ;
    // defparam dsp_alu_0.MULT9_MODE = "DISABLED" ;
    defparam dsp_alu_0.RNDPAT = "0x00000000000000" ;
    defparam dsp_alu_0.MASKPAT = "0x00000000000000" ;
    defparam dsp_alu_0.MCPAT = "0x00000000000000" ;
    defparam dsp_alu_0.MASK01 = "0x00000000000000" ;
    defparam dsp_alu_0.MASKPAT_SOURCE = "STATIC" ;
    defparam dsp_alu_0.MCPAT_SOURCE = "STATIC" ;
    defparam dsp_alu_0.RESETMODE = "SYNC" ;
    defparam dsp_alu_0.GSR = "ENABLED" ;
    ALU54B dsp_alu_0 (.A35(mult2_0_mult_out_rob_2_17), .A34(mult2_0_mult_out_rob_2_16),
        .A33(mult2_0_mult_out_rob_2_15), .A32(mult2_0_mult_out_rob_2_14),
        .A31(mult2_0_mult_out_rob_2_13), .A30(mult2_0_mult_out_rob_2_12),
        .A29(mult2_0_mult_out_rob_2_11), .A28(mult2_0_mult_out_rob_2_10),
        .A27(mult2_0_mult_out_rob_2_9), .A26(mult2_0_mult_out_rob_2_8),
        .A25(mult2_0_mult_out_rob_2_7), .A24(mult2_0_mult_out_rob_2_6),
        .A23(mult2_0_mult_out_rob_2_5), .A22(mult2_0_mult_out_rob_2_4),
        .A21(mult2_0_mult_out_rob_2_3), .A20(mult2_0_mult_out_rob_2_2),
        .A19(mult2_0_mult_out_rob_2_1), .A18(mult2_0_mult_out_rob_2_0),
        .A17(mult2_0_mult_out_roa_2_17), .A16(mult2_0_mult_out_roa_2_16),
        .A15(mult2_0_mult_out_roa_2_15), .A14(mult2_0_mult_out_roa_2_14),
        .A13(mult2_0_mult_out_roa_2_13), .A12(mult2_0_mult_out_roa_2_12),
        .A11(mult2_0_mult_out_roa_2_11), .A10(mult2_0_mult_out_roa_2_10),
        .A9(mult2_0_mult_out_roa_2_9), .A8(mult2_0_mult_out_roa_2_8), .A7(mult2_0_mult_out_roa_2_7),
        .A6(mult2_0_mult_out_roa_2_6), .A5(mult2_0_mult_out_roa_2_5), .A4(mult2_0_mult_out_roa_2_4),
        .A3(mult2_0_mult_out_roa_2_3), .A2(mult2_0_mult_out_roa_2_2), .A1(mult2_0_mult_out_roa_2_1),
        .A0(mult2_0_mult_out_roa_2_0), .B35(mult2_0_mult_out_rob_3_17),
        .B34(mult2_0_mult_out_rob_3_16), .B33(mult2_0_mult_out_rob_3_15),
        .B32(mult2_0_mult_out_rob_3_14), .B31(mult2_0_mult_out_rob_3_13),
        .B30(mult2_0_mult_out_rob_3_12), .B29(mult2_0_mult_out_rob_3_11),
        .B28(mult2_0_mult_out_rob_3_10), .B27(mult2_0_mult_out_rob_3_9),
        .B26(mult2_0_mult_out_rob_3_8), .B25(mult2_0_mult_out_rob_3_7),
        .B24(mult2_0_mult_out_rob_3_6), .B23(mult2_0_mult_out_rob_3_5),
        .B22(mult2_0_mult_out_rob_3_4), .B21(mult2_0_mult_out_rob_3_3),
        .B20(mult2_0_mult_out_rob_3_2), .B19(mult2_0_mult_out_rob_3_1),
        .B18(mult2_0_mult_out_rob_3_0), .B17(mult2_0_mult_out_roa_3_17),
        .B16(mult2_0_mult_out_roa_3_16), .B15(mult2_0_mult_out_roa_3_15),
        .B14(mult2_0_mult_out_roa_3_14), .B13(mult2_0_mult_out_roa_3_13),
        .B12(mult2_0_mult_out_roa_3_12), .B11(mult2_0_mult_out_roa_3_11),
        .B10(mult2_0_mult_out_roa_3_10), .B9(mult2_0_mult_out_roa_3_9),
        .B8(mult2_0_mult_out_roa_3_8), .B7(mult2_0_mult_out_roa_3_7), .B6(mult2_0_mult_out_roa_3_6),
        .B5(mult2_0_mult_out_roa_3_5), .B4(mult2_0_mult_out_roa_3_4), .B3(mult2_0_mult_out_roa_3_3),
        .B2(mult2_0_mult_out_roa_3_2), .B1(mult2_0_mult_out_roa_3_1), .B0(mult2_0_mult_out_roa_3_0),
        .CFB53(1'b0), .CFB52(1'b0), .CFB51(1'b0), .CFB50(1'b0),
        .CFB49(1'b0), .CFB48(1'b0), .CFB47(1'b0), .CFB46(1'b0),
        .CFB45(1'b0), .CFB44(1'b0), .CFB43(1'b0), .CFB42(1'b0),
        .CFB41(1'b0), .CFB40(1'b0), .CFB39(1'b0), .CFB38(1'b0),
        .CFB37(1'b0), .CFB36(1'b0), .CFB35(1'b0), .CFB34(1'b0),
        .CFB33(1'b0), .CFB32(1'b0), .CFB31(1'b0), .CFB30(1'b0),
        .CFB29(1'b0), .CFB28(1'b0), .CFB27(1'b0), .CFB26(1'b0),
        .CFB25(1'b0), .CFB24(1'b0), .CFB23(1'b0), .CFB22(1'b0),
        .CFB21(1'b0), .CFB20(1'b0), .CFB19(1'b0), .CFB18(1'b0),
        .CFB17(1'b0), .CFB16(1'b0), .CFB15(1'b0), .CFB14(1'b0),
        .CFB13(1'b0), .CFB12(1'b0), .CFB11(1'b0), .CFB10(1'b0),
        .CFB9(1'b0), .CFB8(1'b0), .CFB7(1'b0), .CFB6(1'b0),
        .CFB5(1'b0), .CFB4(1'b0), .CFB3(1'b0), .CFB2(1'b0),
        .CFB1(1'b0), .CFB0(1'b0), .C53(1'b0), .C52(1'b0),
        .C51(1'b0), .C50(1'b0), .C49(1'b0), .C48(1'b0),
        .C47(1'b0), .C46(1'b0), .C45(1'b0), .C44(1'b0),
        .C43(1'b0), .C42(1'b0), .C41(1'b0), .C40(1'b0),
        .C39(1'b0), .C38(1'b0), .C37(1'b0), .C36(1'b0),
        .C35(1'b0), .C34(1'b0), .C33(1'b0), .C32(1'b0),
        .C31(1'b0), .C30(1'b0), .C29(1'b0), .C28(1'b0),
        .C27(1'b0), .C26(1'b0), .C25(1'b0), .C24(1'b0),
        .C23(1'b0), .C22(1'b0), .C21(1'b0), .C20(1'b0),
        .C19(1'b0), .C18(1'b0), .C17(1'b0), .C16(1'b0),
        .C15(1'b0), .C14(1'b0), .C13(1'b0), .C12(1'b0),
        .C11(1'b0), .C10(1'b0), .C9(1'b0), .C8(1'b0),
        .C7(1'b0), .C6(1'b0), .C5(1'b0), .C4(1'b0),
        .C3(1'b0), .C2(1'b0), .C1(1'b0), .C0(1'b0),
        .CE0(CE0), .CE1(1'b1), .CE2(1'b1), .CE3(1'b1), .CLK0(CLK0),
        .CLK1(CLK0), .CLK2(1'b0), .CLK3(1'b0), .RST0(RST0), .RST1(1'b0),
        .RST2(1'b0), .RST3(1'b0), .SIGNEDIA(mult2_0_mult_out_signedp_2),
        .SIGNEDIB(mult2_0_mult_out_signedp_3), .SIGNEDCIN(mult2_alu_signedr_1_0),
        .MA35(mult2_0_mult_out_p_2_35), .MA34(mult2_0_mult_out_p_2_34),
        .MA33(mult2_0_mult_out_p_2_33), .MA32(mult2_0_mult_out_p_2_32),
        .MA31(mult2_0_mult_out_p_2_31), .MA30(mult2_0_mult_out_p_2_30),
        .MA29(mult2_0_mult_out_p_2_29), .MA28(mult2_0_mult_out_p_2_28),
        .MA27(mult2_0_mult_out_p_2_27), .MA26(mult2_0_mult_out_p_2_26),
        .MA25(mult2_0_mult_out_p_2_25), .MA24(mult2_0_mult_out_p_2_24),
        .MA23(mult2_0_mult_out_p_2_23), .MA22(mult2_0_mult_out_p_2_22),
        .MA21(mult2_0_mult_out_p_2_21), .MA20(mult2_0_mult_out_p_2_20),
        .MA19(mult2_0_mult_out_p_2_19), .MA18(mult2_0_mult_out_p_2_18),
        .MA17(mult2_0_mult_out_p_2_17), .MA16(mult2_0_mult_out_p_2_16),
        .MA15(mult2_0_mult_out_p_2_15), .MA14(mult2_0_mult_out_p_2_14),
        .MA13(mult2_0_mult_out_p_2_13), .MA12(mult2_0_mult_out_p_2_12),
        .MA11(mult2_0_mult_out_p_2_11), .MA10(mult2_0_mult_out_p_2_10),
        .MA9(mult2_0_mult_out_p_2_9), .MA8(mult2_0_mult_out_p_2_8), .MA7(mult2_0_mult_out_p_2_7),
        .MA6(mult2_0_mult_out_p_2_6), .MA5(mult2_0_mult_out_p_2_5), .MA4(mult2_0_mult_out_p_2_4),
        .MA3(mult2_0_mult_out_p_2_3), .MA2(mult2_0_mult_out_p_2_2), .MA1(mult2_0_mult_out_p_2_1),
        .MA0(mult2_0_mult_out_p_2_0), .MB35(mult2_0_mult_out_p_3_35), .MB34(mult2_0_mult_out_p_3_34),
        .MB33(mult2_0_mult_out_p_3_33), .MB32(mult2_0_mult_out_p_3_32),
        .MB31(mult2_0_mult_out_p_3_31), .MB30(mult2_0_mult_out_p_3_30),
        .MB29(mult2_0_mult_out_p_3_29), .MB28(mult2_0_mult_out_p_3_28),
        .MB27(mult2_0_mult_out_p_3_27), .MB26(mult2_0_mult_out_p_3_26),
        .MB25(mult2_0_mult_out_p_3_25), .MB24(mult2_0_mult_out_p_3_24),
        .MB23(mult2_0_mult_out_p_3_23), .MB22(mult2_0_mult_out_p_3_22),
        .MB21(mult2_0_mult_out_p_3_21), .MB20(mult2_0_mult_out_p_3_20),
        .MB19(mult2_0_mult_out_p_3_19), .MB18(mult2_0_mult_out_p_3_18),
        .MB17(mult2_0_mult_out_p_3_17), .MB16(mult2_0_mult_out_p_3_16),
        .MB15(mult2_0_mult_out_p_3_15), .MB14(mult2_0_mult_out_p_3_14),
        .MB13(mult2_0_mult_out_p_3_13), .MB12(mult2_0_mult_out_p_3_12),
        .MB11(mult2_0_mult_out_p_3_11), .MB10(mult2_0_mult_out_p_3_10),
        .MB9(mult2_0_mult_out_p_3_9), .MB8(mult2_0_mult_out_p_3_8), .MB7(mult2_0_mult_out_p_3_7),
        .MB6(mult2_0_mult_out_p_3_6), .MB5(mult2_0_mult_out_p_3_5), .MB4(mult2_0_mult_out_p_3_4),
        .MB3(mult2_0_mult_out_p_3_3), .MB2(mult2_0_mult_out_p_3_2), .MB1(mult2_0_mult_out_p_3_1),
        .MB0(mult2_0_mult_out_p_3_0), .CIN53(mult2_alu_output_r_1_0_53),
        .CIN52(mult2_alu_output_r_1_0_52), .CIN51(mult2_alu_output_r_1_0_51),
        .CIN50(mult2_alu_output_r_1_0_50), .CIN49(mult2_alu_output_r_1_0_49),
        .CIN48(mult2_alu_output_r_1_0_48), .CIN47(mult2_alu_output_r_1_0_47),
        .CIN46(mult2_alu_output_r_1_0_46), .CIN45(mult2_alu_output_r_1_0_45),
        .CIN44(mult2_alu_output_r_1_0_44), .CIN43(mult2_alu_output_r_1_0_43),
        .CIN42(mult2_alu_output_r_1_0_42), .CIN41(mult2_alu_output_r_1_0_41),
        .CIN40(mult2_alu_output_r_1_0_40), .CIN39(mult2_alu_output_r_1_0_39),
        .CIN38(mult2_alu_output_r_1_0_38), .CIN37(mult2_alu_output_r_1_0_37),
        .CIN36(mult2_alu_output_r_1_0_36), .CIN35(mult2_alu_output_r_1_0_35),
        .CIN34(mult2_alu_output_r_1_0_34), .CIN33(mult2_alu_output_r_1_0_33),
        .CIN32(mult2_alu_output_r_1_0_32), .CIN31(mult2_alu_output_r_1_0_31),
        .CIN30(mult2_alu_output_r_1_0_30), .CIN29(mult2_alu_output_r_1_0_29),
        .CIN28(mult2_alu_output_r_1_0_28), .CIN27(mult2_alu_output_r_1_0_27),
        .CIN26(mult2_alu_output_r_1_0_26), .CIN25(mult2_alu_output_r_1_0_25),
        .CIN24(mult2_alu_output_r_1_0_24), .CIN23(mult2_alu_output_r_1_0_23),
        .CIN22(mult2_alu_output_r_1_0_22), .CIN21(mult2_alu_output_r_1_0_21),
        .CIN20(mult2_alu_output_r_1_0_20), .CIN19(mult2_alu_output_r_1_0_19),
        .CIN18(mult2_alu_output_r_1_0_18), .CIN17(mult2_alu_output_r_1_0_17),
        .CIN16(mult2_alu_output_r_1_0_16), .CIN15(mult2_alu_output_r_1_0_15),
        .CIN14(mult2_alu_output_r_1_0_14), .CIN13(mult2_alu_output_r_1_0_13),
        .CIN12(mult2_alu_output_r_1_0_12), .CIN11(mult2_alu_output_r_1_0_11),
        .CIN10(mult2_alu_output_r_1_0_10), .CIN9(mult2_alu_output_r_1_0_9),
        .CIN8(mult2_alu_output_r_1_0_8), .CIN7(mult2_alu_output_r_1_0_7),
        .CIN6(mult2_alu_output_r_1_0_6), .CIN5(mult2_alu_output_r_1_0_5),
        .CIN4(mult2_alu_output_r_1_0_4), .CIN3(mult2_alu_output_r_1_0_3),
        .CIN2(mult2_alu_output_r_1_0_2), .CIN1(mult2_alu_output_r_1_0_1),
        .CIN0(mult2_alu_output_r_1_0_0), .OP10(1'b0), .OP9(1'b1),
        .OP8(1'b0), .OP7(1'b0), .OP6(1'b0), .OP5(1'b0),
        .OP4(1'b1), .OP3(1'b0), .OP2(1'b0), .OP1(1'b0),
        .OP0(1'b1), .R53(mult2_alu_output_r_2_1_53), .R52(mult2_alu_output_r_2_1_52),
        .R51(mult2_alu_output_r_2_1_51), .R50(mult2_alu_output_r_2_1_50),
        .R49(mult2_alu_output_r_2_1_49), .R48(mult2_alu_output_r_2_1_48),
        .R47(mult2_alu_output_r_2_1_47), .R46(mult2_alu_output_r_2_1_46),
        .R45(mult2_alu_output_r_2_1_45), .R44(mult2_alu_output_r_2_1_44),
        .R43(mult2_alu_output_r_2_1_43), .R42(mult2_alu_output_r_2_1_42),
        .R41(mult2_alu_output_r_2_1_41), .R40(mult2_alu_output_r_2_1_40),
        .R39(mult2_alu_output_r_2_1_39), .R38(mult2_alu_output_r_2_1_38),
        .R37(mult2_alu_output_r_2_1_37), .R36(mult2_alu_output_r_2_1_36),
        .R35(mult2_alu_output_r_2_1_35), .R34(mult2_alu_output_r_2_1_34),
        .R33(mult2_alu_output_r_2_1_33), .R32(mult2_alu_output_r_2_1_32),
        .R31(mult2_alu_output_r_2_1_31), .R30(mult2_alu_output_r_2_1_30),
        .R29(mult2_alu_output_r_2_1_29), .R28(mult2_alu_output_r_2_1_28),
        .R27(mult2_alu_output_r_2_1_27), .R26(mult2_alu_output_r_2_1_26),
        .R25(mult2_alu_output_r_2_1_25), .R24(mult2_alu_output_r_2_1_24),
        .R23(mult2_alu_output_r_2_1_23), .R22(mult2_alu_output_r_2_1_22),
        .R21(mult2_alu_output_r_2_1_21), .R20(mult2_alu_output_r_2_1_20),
        .R19(mult2_alu_output_r_2_1_19), .R18(mult2_alu_output_r_2_1_18),
        .R17(mult2_alu_output_r_2_1_17), .R16(mult2_alu_output_r_2_1_16),
        .R15(mult2_alu_output_r_2_1_15), .R14(mult2_alu_output_r_2_1_14),
        .R13(mult2_alu_output_r_2_1_13), .R12(mult2_alu_output_r_2_1_12),
        .R11(mult2_alu_output_r_2_1_11), .R10(mult2_alu_output_r_2_1_10),
        .R9(mult2_alu_output_r_2_1_9), .R8(mult2_alu_output_r_2_1_8), .R7(mult2_alu_output_r_2_1_7),
        .R6(mult2_alu_output_r_2_1_6), .R5(mult2_alu_output_r_2_1_5), .R4(mult2_alu_output_r_2_1_4),
        .R3(mult2_alu_output_r_2_1_3), .R2(mult2_alu_output_r_2_1_2), .R1(mult2_alu_output_r_2_1_1),
        .R0(mult2_alu_output_r_2_1_0), .CO53(), .CO52(), .CO51(), .CO50(),
        .CO49(), .CO48(), .CO47(), .CO46(), .CO45(), .CO44(), .CO43(), .CO42(),
        .CO41(), .CO40(), .CO39(), .CO38(), .CO37(), .CO36(), .CO35(), .CO34(),
        .CO33(), .CO32(), .CO31(), .CO30(), .CO29(), .CO28(), .CO27(), .CO26(),
        .CO25(), .CO24(), .CO23(), .CO22(), .CO21(), .CO20(), .CO19(), .CO18(),
        .CO17(), .CO16(), .CO15(), .CO14(), .CO13(), .CO12(), .CO11(), .CO10(),
        .CO9(), .CO8(), .CO7(), .CO6(), .CO5(), .CO4(), .CO3(), .CO2(),
        .CO1(), .CO0(), .EQZ(), .EQZM(), .EQOM(), .EQPAT(), .EQPATB(), .OVER(),
        .UNDER(), .OVERUNDER(), .SIGNEDR(mult2_alu_signedr_2_1));

    defparam dsp_mult_3.CLK3_DIV = "ENABLED" ;
    defparam dsp_mult_3.CLK2_DIV = "ENABLED" ;
    defparam dsp_mult_3.CLK1_DIV = "ENABLED" ;
    defparam dsp_mult_3.CLK0_DIV = "ENABLED" ;
    // defparam dsp_mult_3.HIGHSPEED_CLK = "NONE" ;
    // defparam dsp_mult_3.REG_INPUTC_RST = "RST0" ;
    // defparam dsp_mult_3.REG_INPUTC_CE = "CE0" ;
    defparam dsp_mult_3.REG_INPUTC_CLK = "NONE" ;
    defparam dsp_mult_3.SOURCEB_MODE = "B_SHIFT" ;
    // defparam dsp_mult_3.MULT_BYPASS = "DISABLED" ;
    // defparam dsp_mult_3.CAS_MATCH_REG = "FALSE" ;
    defparam dsp_mult_3.RESETMODE = "SYNC" ;
    defparam dsp_mult_3.GSR = "ENABLED" ;
    // defparam dsp_mult_3.REG_OUTPUT_RST = "RST0" ;
    // defparam dsp_mult_3.REG_OUTPUT_CE = "CE0" ;
    defparam dsp_mult_3.REG_OUTPUT_CLK = "NONE" ;
    defparam dsp_mult_3.REG_PIPELINE_RST = "RST0" ;
    defparam dsp_mult_3.REG_PIPELINE_CE = "CE0" ;
    defparam dsp_mult_3.REG_PIPELINE_CLK = "CLK0" ;
    defparam dsp_mult_3.REG_INPUTB_RST = "RST0" ;
    defparam dsp_mult_3.REG_INPUTB_CE = "CE0" ;
    defparam dsp_mult_3.REG_INPUTB_CLK = "CLK0" ;
    defparam dsp_mult_3.REG_INPUTA_RST = "RST0" ;
    defparam dsp_mult_3.REG_INPUTA_CE = "CE0" ;
    defparam dsp_mult_3.REG_INPUTA_CLK = "CLK0" ;
    MULT18X18D dsp_mult_3 (.A17(A[17]), .A16(A[16]), .A15(A[15]), .A14(A[14]),
        .A13(A[13]), .A12(A[12]), .A11(A[11]), .A10(A[10]), .A9(A[9]), .A8(A[8]),
        .A7(A[7]), .A6(A[6]), .A5(A[5]), .A4(A[4]), .A3(A[3]), .A2(A[2]),
        .A1(A[1]), .A0(A[0]), .B17(B[17]), .B16(B[16]), .B15(B[15]), .B14(B[14]),
        .B13(B[13]), .B12(B[12]), .B11(B[11]), .B10(B[10]), .B9(B[9]), .B8(B[8]),
        .B7(B[7]), .B6(B[6]), .B5(B[5]), .B4(B[4]), .B3(B[3]), .B2(B[2]),
        .B1(B[1]), .B0(B[0]), .C17(1'b0), .C16(1'b0), .C15(1'b0),
        .C14(1'b0), .C13(1'b0), .C12(1'b0), .C11(1'b0),
        .C10(1'b0), .C9(1'b0), .C8(1'b0), .C7(1'b0),
        .C6(1'b0), .C5(1'b0), .C4(1'b0), .C3(1'b0),
        .C2(1'b0), .C1(1'b0), .C0(1'b0), .SIGNEDA(1'b0),
        .SIGNEDB(1'b0), .SOURCEA(1'b0), .SOURCEB(1'b0), .CE0(CE0),
        .CE1(1'b1), .CE2(1'b1), .CE3(1'b1), .CLK0(CLK0),
        .CLK1(1'b0), .CLK2(1'b0), .CLK3(1'b0), .RST0(RST0),
        .RST1(1'b0), .RST2(1'b0), .RST3(1'b0), .SRIA17(1'b0),
        .SRIA16(1'b0), .SRIA15(1'b0), .SRIA14(1'b0), .SRIA13(1'b0),
        .SRIA12(1'b0), .SRIA11(1'b0), .SRIA10(1'b0), .SRIA9(1'b0),
        .SRIA8(1'b0), .SRIA7(1'b0), .SRIA6(1'b0), .SRIA5(1'b0),
        .SRIA4(1'b0), .SRIA3(1'b0), .SRIA2(1'b0), .SRIA1(1'b0),
        .SRIA0(1'b0), .SRIB17(1'b0), .SRIB16(1'b0), .SRIB15(1'b0),
        .SRIB14(1'b0), .SRIB13(1'b0), .SRIB12(1'b0), .SRIB11(1'b0),
        .SRIB10(1'b0), .SRIB9(1'b0), .SRIB8(1'b0), .SRIB7(1'b0),
        .SRIB6(1'b0), .SRIB5(1'b0), .SRIB4(1'b0), .SRIB3(1'b0),
        .SRIB2(1'b0), .SRIB1(1'b0), .SRIB0(1'b0), .SROA17(),
        .SROA16(), .SROA15(), .SROA14(), .SROA13(), .SROA12(), .SROA11(),
        .SROA10(), .SROA9(), .SROA8(), .SROA7(), .SROA6(), .SROA5(), .SROA4(),
        .SROA3(), .SROA2(), .SROA1(), .SROA0(), .SROB17(), .SROB16(), .SROB15(),
        .SROB14(), .SROB13(), .SROB12(), .SROB11(), .SROB10(), .SROB9(),
        .SROB8(), .SROB7(), .SROB6(), .SROB5(), .SROB4(), .SROB3(), .SROB2(),
        .SROB1(), .SROB0(), .ROA17(mult2_0_mult_out_roa_0_17), .ROA16(mult2_0_mult_out_roa_0_16),
        .ROA15(mult2_0_mult_out_roa_0_15), .ROA14(mult2_0_mult_out_roa_0_14),
        .ROA13(mult2_0_mult_out_roa_0_13), .ROA12(mult2_0_mult_out_roa_0_12),
        .ROA11(mult2_0_mult_out_roa_0_11), .ROA10(mult2_0_mult_out_roa_0_10),
        .ROA9(mult2_0_mult_out_roa_0_9), .ROA8(mult2_0_mult_out_roa_0_8),
        .ROA7(mult2_0_mult_out_roa_0_7), .ROA6(mult2_0_mult_out_roa_0_6),
        .ROA5(mult2_0_mult_out_roa_0_5), .ROA4(mult2_0_mult_out_roa_0_4),
        .ROA3(mult2_0_mult_out_roa_0_3), .ROA2(mult2_0_mult_out_roa_0_2),
        .ROA1(mult2_0_mult_out_roa_0_1), .ROA0(mult2_0_mult_out_roa_0_0),
        .ROB17(mult2_0_mult_out_rob_0_17), .ROB16(mult2_0_mult_out_rob_0_16),
        .ROB15(mult2_0_mult_out_rob_0_15), .ROB14(mult2_0_mult_out_rob_0_14),
        .ROB13(mult2_0_mult_out_rob_0_13), .ROB12(mult2_0_mult_out_rob_0_12),
        .ROB11(mult2_0_mult_out_rob_0_11), .ROB10(mult2_0_mult_out_rob_0_10),
        .ROB9(mult2_0_mult_out_rob_0_9), .ROB8(mult2_0_mult_out_rob_0_8),
        .ROB7(mult2_0_mult_out_rob_0_7), .ROB6(mult2_0_mult_out_rob_0_6),
        .ROB5(mult2_0_mult_out_rob_0_5), .ROB4(mult2_0_mult_out_rob_0_4),
        .ROB3(mult2_0_mult_out_rob_0_3), .ROB2(mult2_0_mult_out_rob_0_2),
        .ROB1(mult2_0_mult_out_rob_0_1), .ROB0(mult2_0_mult_out_rob_0_0),
        .ROC17(), .ROC16(), .ROC15(), .ROC14(), .ROC13(), .ROC12(), .ROC11(),
        .ROC10(), .ROC9(), .ROC8(), .ROC7(), .ROC6(), .ROC5(), .ROC4(),
        .ROC3(), .ROC2(), .ROC1(), .ROC0(), .P35(mult2_0_mult_out_p_0_35),
        .P34(mult2_0_mult_out_p_0_34), .P33(mult2_0_mult_out_p_0_33), .P32(mult2_0_mult_out_p_0_32),
        .P31(mult2_0_mult_out_p_0_31), .P30(mult2_0_mult_out_p_0_30), .P29(mult2_0_mult_out_p_0_29),
        .P28(mult2_0_mult_out_p_0_28), .P27(mult2_0_mult_out_p_0_27), .P26(mult2_0_mult_out_p_0_26),
        .P25(mult2_0_mult_out_p_0_25), .P24(mult2_0_mult_out_p_0_24), .P23(mult2_0_mult_out_p_0_23),
        .P22(mult2_0_mult_out_p_0_22), .P21(mult2_0_mult_out_p_0_21), .P20(mult2_0_mult_out_p_0_20),
        .P19(mult2_0_mult_out_p_0_19), .P18(mult2_0_mult_out_p_0_18), .P17(mult2_0_mult_out_p_0_17),
        .P16(mult2_0_mult_out_p_0_16), .P15(mult2_0_mult_out_p_0_15), .P14(mult2_0_mult_out_p_0_14),
        .P13(mult2_0_mult_out_p_0_13), .P12(mult2_0_mult_out_p_0_12), .P11(mult2_0_mult_out_p_0_11),
        .P10(mult2_0_mult_out_p_0_10), .P9(mult2_0_mult_out_p_0_9), .P8(mult2_0_mult_out_p_0_8),
        .P7(mult2_0_mult_out_p_0_7), .P6(mult2_0_mult_out_p_0_6), .P5(mult2_0_mult_out_p_0_5),
        .P4(mult2_0_mult_out_p_0_4), .P3(mult2_0_mult_out_p_0_3), .P2(mult2_0_mult_out_p_0_2),
        .P1(mult2_0_mult_out_p_0_1), .P0(mult2_0_mult_out_p_0_0), .SIGNEDP(mult2_0_mult_out_signedp_0));

    defparam dsp_mult_2.CLK3_DIV = "ENABLED" ;
    defparam dsp_mult_2.CLK2_DIV = "ENABLED" ;
    defparam dsp_mult_2.CLK1_DIV = "ENABLED" ;
    defparam dsp_mult_2.CLK0_DIV = "ENABLED" ;
    // defparam dsp_mult_2.HIGHSPEED_CLK = "NONE" ;
    // defparam dsp_mult_2.REG_INPUTC_RST = "RST0" ;
    // defparam dsp_mult_2.REG_INPUTC_CE = "CE0" ;
    defparam dsp_mult_2.REG_INPUTC_CLK = "NONE" ;
    defparam dsp_mult_2.SOURCEB_MODE = "B_SHIFT" ;
    // defparam dsp_mult_2.MULT_BYPASS = "DISABLED" ;
    // defparam dsp_mult_2.CAS_MATCH_REG = "FALSE" ;
    defparam dsp_mult_2.RESETMODE = "SYNC" ;
    defparam dsp_mult_2.GSR = "ENABLED" ;
    // defparam dsp_mult_2.REG_OUTPUT_RST = "RST0" ;
    // defparam dsp_mult_2.REG_OUTPUT_CE = "CE0" ;
    defparam dsp_mult_2.REG_OUTPUT_CLK = "NONE" ;
    defparam dsp_mult_2.REG_PIPELINE_RST = "RST0" ;
    defparam dsp_mult_2.REG_PIPELINE_CE = "CE0" ;
    defparam dsp_mult_2.REG_PIPELINE_CLK = "CLK0" ;
    defparam dsp_mult_2.REG_INPUTB_RST = "RST0" ;
    defparam dsp_mult_2.REG_INPUTB_CE = "CE0" ;
    defparam dsp_mult_2.REG_INPUTB_CLK = "CLK0" ;
    defparam dsp_mult_2.REG_INPUTA_RST = "RST0" ;
    defparam dsp_mult_2.REG_INPUTA_CE = "CE0" ;
    defparam dsp_mult_2.REG_INPUTA_CLK = "CLK0" ;
    MULT18X18D dsp_mult_2 (.A17(A[35]), .A16(A[34]), .A15(A[33]), .A14(A[32]),
        .A13(A[31]), .A12(A[30]), .A11(A[29]), .A10(A[28]), .A9(A[27]),
        .A8(A[26]), .A7(A[25]), .A6(A[24]), .A5(A[23]), .A4(A[22]), .A3(A[21]),
        .A2(A[20]), .A1(A[19]), .A0(A[18]), .B17(B[17]), .B16(B[16]), .B15(B[15]),
        .B14(B[14]), .B13(B[13]), .B12(B[12]), .B11(B[11]), .B10(B[10]),
        .B9(B[9]), .B8(B[8]), .B7(B[7]), .B6(B[6]), .B5(B[5]), .B4(B[4]),
        .B3(B[3]), .B2(B[2]), .B1(B[1]), .B0(B[0]), .C17(1'b0), .C16(1'b0),
        .C15(1'b0), .C14(1'b0), .C13(1'b0), .C12(1'b0),
        .C11(1'b0), .C10(1'b0), .C9(1'b0), .C8(1'b0),
        .C7(1'b0), .C6(1'b0), .C5(1'b0), .C4(1'b0),
        .C3(1'b0), .C2(1'b0), .C1(1'b0), .C0(1'b0),
        .SIGNEDA(1'b1), .SIGNEDB(1'b0), .SOURCEA(1'b0), .SOURCEB(1'b0),
        .CE0(CE0), .CE1(1'b1), .CE2(1'b1), .CE3(1'b1), .CLK0(CLK0),
        .CLK1(1'b0), .CLK2(1'b0), .CLK3(1'b0), .RST0(RST0),
        .RST1(1'b0), .RST2(1'b0), .RST3(1'b0), .SRIA17(1'b0),
        .SRIA16(1'b0), .SRIA15(1'b0), .SRIA14(1'b0), .SRIA13(1'b0),
        .SRIA12(1'b0), .SRIA11(1'b0), .SRIA10(1'b0), .SRIA9(1'b0),
        .SRIA8(1'b0), .SRIA7(1'b0), .SRIA6(1'b0), .SRIA5(1'b0),
        .SRIA4(1'b0), .SRIA3(1'b0), .SRIA2(1'b0), .SRIA1(1'b0),
        .SRIA0(1'b0), .SRIB17(1'b0), .SRIB16(1'b0), .SRIB15(1'b0),
        .SRIB14(1'b0), .SRIB13(1'b0), .SRIB12(1'b0), .SRIB11(1'b0),
        .SRIB10(1'b0), .SRIB9(1'b0), .SRIB8(1'b0), .SRIB7(1'b0),
        .SRIB6(1'b0), .SRIB5(1'b0), .SRIB4(1'b0), .SRIB3(1'b0),
        .SRIB2(1'b0), .SRIB1(1'b0), .SRIB0(1'b0), .SROA17(),
        .SROA16(), .SROA15(), .SROA14(), .SROA13(), .SROA12(), .SROA11(),
        .SROA10(), .SROA9(), .SROA8(), .SROA7(), .SROA6(), .SROA5(), .SROA4(),
        .SROA3(), .SROA2(), .SROA1(), .SROA0(), .SROB17(), .SROB16(), .SROB15(),
        .SROB14(), .SROB13(), .SROB12(), .SROB11(), .SROB10(), .SROB9(),
        .SROB8(), .SROB7(), .SROB6(), .SROB5(), .SROB4(), .SROB3(), .SROB2(),
        .SROB1(), .SROB0(), .ROA17(mult2_0_mult_out_roa_1_17), .ROA16(mult2_0_mult_out_roa_1_16),
        .ROA15(mult2_0_mult_out_roa_1_15), .ROA14(mult2_0_mult_out_roa_1_14),
        .ROA13(mult2_0_mult_out_roa_1_13), .ROA12(mult2_0_mult_out_roa_1_12),
        .ROA11(mult2_0_mult_out_roa_1_11), .ROA10(mult2_0_mult_out_roa_1_10),
        .ROA9(mult2_0_mult_out_roa_1_9), .ROA8(mult2_0_mult_out_roa_1_8),
        .ROA7(mult2_0_mult_out_roa_1_7), .ROA6(mult2_0_mult_out_roa_1_6),
        .ROA5(mult2_0_mult_out_roa_1_5), .ROA4(mult2_0_mult_out_roa_1_4),
        .ROA3(mult2_0_mult_out_roa_1_3), .ROA2(mult2_0_mult_out_roa_1_2),
        .ROA1(mult2_0_mult_out_roa_1_1), .ROA0(mult2_0_mult_out_roa_1_0),
        .ROB17(mult2_0_mult_out_rob_1_17), .ROB16(mult2_0_mult_out_rob_1_16),
        .ROB15(mult2_0_mult_out_rob_1_15), .ROB14(mult2_0_mult_out_rob_1_14),
        .ROB13(mult2_0_mult_out_rob_1_13), .ROB12(mult2_0_mult_out_rob_1_12),
        .ROB11(mult2_0_mult_out_rob_1_11), .ROB10(mult2_0_mult_out_rob_1_10),
        .ROB9(mult2_0_mult_out_rob_1_9), .ROB8(mult2_0_mult_out_rob_1_8),
        .ROB7(mult2_0_mult_out_rob_1_7), .ROB6(mult2_0_mult_out_rob_1_6),
        .ROB5(mult2_0_mult_out_rob_1_5), .ROB4(mult2_0_mult_out_rob_1_4),
        .ROB3(mult2_0_mult_out_rob_1_3), .ROB2(mult2_0_mult_out_rob_1_2),
        .ROB1(mult2_0_mult_out_rob_1_1), .ROB0(mult2_0_mult_out_rob_1_0),
        .ROC17(), .ROC16(), .ROC15(), .ROC14(), .ROC13(), .ROC12(), .ROC11(),
        .ROC10(), .ROC9(), .ROC8(), .ROC7(), .ROC6(), .ROC5(), .ROC4(),
        .ROC3(), .ROC2(), .ROC1(), .ROC0(), .P35(mult2_0_mult_out_p_1_35),
        .P34(mult2_0_mult_out_p_1_34), .P33(mult2_0_mult_out_p_1_33), .P32(mult2_0_mult_out_p_1_32),
        .P31(mult2_0_mult_out_p_1_31), .P30(mult2_0_mult_out_p_1_30), .P29(mult2_0_mult_out_p_1_29),
        .P28(mult2_0_mult_out_p_1_28), .P27(mult2_0_mult_out_p_1_27), .P26(mult2_0_mult_out_p_1_26),
        .P25(mult2_0_mult_out_p_1_25), .P24(mult2_0_mult_out_p_1_24), .P23(mult2_0_mult_out_p_1_23),
        .P22(mult2_0_mult_out_p_1_22), .P21(mult2_0_mult_out_p_1_21), .P20(mult2_0_mult_out_p_1_20),
        .P19(mult2_0_mult_out_p_1_19), .P18(mult2_0_mult_out_p_1_18), .P17(mult2_0_mult_out_p_1_17),
        .P16(mult2_0_mult_out_p_1_16), .P15(mult2_0_mult_out_p_1_15), .P14(mult2_0_mult_out_p_1_14),
        .P13(mult2_0_mult_out_p_1_13), .P12(mult2_0_mult_out_p_1_12), .P11(mult2_0_mult_out_p_1_11),
        .P10(mult2_0_mult_out_p_1_10), .P9(mult2_0_mult_out_p_1_9), .P8(mult2_0_mult_out_p_1_8),
        .P7(mult2_0_mult_out_p_1_7), .P6(mult2_0_mult_out_p_1_6), .P5(mult2_0_mult_out_p_1_5),
        .P4(mult2_0_mult_out_p_1_4), .P3(mult2_0_mult_out_p_1_3), .P2(mult2_0_mult_out_p_1_2),
        .P1(mult2_0_mult_out_p_1_1), .P0(mult2_0_mult_out_p_1_0), .SIGNEDP(mult2_0_mult_out_signedp_1));

    defparam dsp_mult_1.CLK3_DIV = "ENABLED" ;
    defparam dsp_mult_1.CLK2_DIV = "ENABLED" ;
    defparam dsp_mult_1.CLK1_DIV = "ENABLED" ;
    defparam dsp_mult_1.CLK0_DIV = "ENABLED" ;
    // defparam dsp_mult_1.HIGHSPEED_CLK = "NONE" ;
    // defparam dsp_mult_1.REG_INPUTC_RST = "RST0" ;
    // defparam dsp_mult_1.REG_INPUTC_CE = "CE0" ;
    defparam dsp_mult_1.REG_INPUTC_CLK = "NONE" ;
    defparam dsp_mult_1.SOURCEB_MODE = "B_SHIFT" ;
    // defparam dsp_mult_1.MULT_BYPASS = "DISABLED" ;
    // defparam dsp_mult_1.CAS_MATCH_REG = "FALSE" ;
    defparam dsp_mult_1.RESETMODE = "SYNC" ;
    defparam dsp_mult_1.GSR = "ENABLED" ;
    // defparam dsp_mult_1.REG_OUTPUT_RST = "RST0" ;
    // defparam dsp_mult_1.REG_OUTPUT_CE = "CE0" ;
    defparam dsp_mult_1.REG_OUTPUT_CLK = "NONE" ;
    defparam dsp_mult_1.REG_PIPELINE_RST = "RST0" ;
    defparam dsp_mult_1.REG_PIPELINE_CE = "CE0" ;
    defparam dsp_mult_1.REG_PIPELINE_CLK = "CLK0" ;
    defparam dsp_mult_1.REG_INPUTB_RST = "RST0" ;
    defparam dsp_mult_1.REG_INPUTB_CE = "CE0" ;
    defparam dsp_mult_1.REG_INPUTB_CLK = "CLK0" ;
    defparam dsp_mult_1.REG_INPUTA_RST = "RST0" ;
    defparam dsp_mult_1.REG_INPUTA_CE = "CE0" ;
    defparam dsp_mult_1.REG_INPUTA_CLK = "CLK0" ;
    MULT18X18D dsp_mult_1 (.A17(mdina3_r_17), .A16(mdina3_r_16), .A15(mdina3_r_15),
        .A14(mdina3_r_14), .A13(mdina3_r_13), .A12(mdina3_r_12), .A11(mdina3_r_11),
        .A10(mdina3_r_10), .A9(mdina3_r_9), .A8(mdina3_r_8), .A7(mdina3_r_7),
        .A6(mdina3_r_6), .A5(mdina3_r_5), .A4(mdina3_r_4), .A3(mdina3_r_3),
        .A2(mdina3_r_2), .A1(mdina3_r_1), .A0(mdina3_r), .B17(mdinb3_r_17),
        .B16(mdinb3_r_16), .B15(mdinb3_r_15), .B14(mdinb3_r_14), .B13(mdinb3_r_13),
        .B12(mdinb3_r_12), .B11(mdinb3_r_11), .B10(mdinb3_r_10), .B9(mdinb3_r_9),
        .B8(mdinb3_r_8), .B7(mdinb3_r_7), .B6(mdinb3_r_6), .B5(mdinb3_r_5),
        .B4(mdinb3_r_4), .B3(mdinb3_r_3), .B2(mdinb3_r_2), .B1(mdinb3_r_1),
        .B0(mdinb3_r), .C17(1'b0), .C16(1'b0), .C15(1'b0),
        .C14(1'b0), .C13(1'b0), .C12(1'b0), .C11(1'b0),
        .C10(1'b0), .C9(1'b0), .C8(1'b0), .C7(1'b0),
        .C6(1'b0), .C5(1'b0), .C4(1'b0), .C3(1'b0),
        .C2(1'b0), .C1(1'b0), .C0(1'b0), .SIGNEDA(1'b0),
        .SIGNEDB(1'b1), .SOURCEA(1'b0), .SOURCEB(1'b0), .CE0(CE0),
        .CE1(1'b1), .CE2(1'b1), .CE3(1'b1), .CLK0(CLK0),
        .CLK1(1'b0), .CLK2(1'b0), .CLK3(1'b0), .RST0(RST0),
        .RST1(1'b0), .RST2(1'b0), .RST3(1'b0), .SRIA17(1'b0),
        .SRIA16(1'b0), .SRIA15(1'b0), .SRIA14(1'b0), .SRIA13(1'b0),
        .SRIA12(1'b0), .SRIA11(1'b0), .SRIA10(1'b0), .SRIA9(1'b0),
        .SRIA8(1'b0), .SRIA7(1'b0), .SRIA6(1'b0), .SRIA5(1'b0),
        .SRIA4(1'b0), .SRIA3(1'b0), .SRIA2(1'b0), .SRIA1(1'b0),
        .SRIA0(1'b0), .SRIB17(1'b0), .SRIB16(1'b0), .SRIB15(1'b0),
        .SRIB14(1'b0), .SRIB13(1'b0), .SRIB12(1'b0), .SRIB11(1'b0),
        .SRIB10(1'b0), .SRIB9(1'b0), .SRIB8(1'b0), .SRIB7(1'b0),
        .SRIB6(1'b0), .SRIB5(1'b0), .SRIB4(1'b0), .SRIB3(1'b0),
        .SRIB2(1'b0), .SRIB1(1'b0), .SRIB0(1'b0), .SROA17(),
        .SROA16(), .SROA15(), .SROA14(), .SROA13(), .SROA12(), .SROA11(),
        .SROA10(), .SROA9(), .SROA8(), .SROA7(), .SROA6(), .SROA5(), .SROA4(),
        .SROA3(), .SROA2(), .SROA1(), .SROA0(), .SROB17(), .SROB16(), .SROB15(),
        .SROB14(), .SROB13(), .SROB12(), .SROB11(), .SROB10(), .SROB9(),
        .SROB8(), .SROB7(), .SROB6(), .SROB5(), .SROB4(), .SROB3(), .SROB2(),
        .SROB1(), .SROB0(), .ROA17(mult2_0_mult_out_roa_2_17), .ROA16(mult2_0_mult_out_roa_2_16),
        .ROA15(mult2_0_mult_out_roa_2_15), .ROA14(mult2_0_mult_out_roa_2_14),
        .ROA13(mult2_0_mult_out_roa_2_13), .ROA12(mult2_0_mult_out_roa_2_12),
        .ROA11(mult2_0_mult_out_roa_2_11), .ROA10(mult2_0_mult_out_roa_2_10),
        .ROA9(mult2_0_mult_out_roa_2_9), .ROA8(mult2_0_mult_out_roa_2_8),
        .ROA7(mult2_0_mult_out_roa_2_7), .ROA6(mult2_0_mult_out_roa_2_6),
        .ROA5(mult2_0_mult_out_roa_2_5), .ROA4(mult2_0_mult_out_roa_2_4),
        .ROA3(mult2_0_mult_out_roa_2_3), .ROA2(mult2_0_mult_out_roa_2_2),
        .ROA1(mult2_0_mult_out_roa_2_1), .ROA0(mult2_0_mult_out_roa_2_0),
        .ROB17(mult2_0_mult_out_rob_2_17), .ROB16(mult2_0_mult_out_rob_2_16),
        .ROB15(mult2_0_mult_out_rob_2_15), .ROB14(mult2_0_mult_out_rob_2_14),
        .ROB13(mult2_0_mult_out_rob_2_13), .ROB12(mult2_0_mult_out_rob_2_12),
        .ROB11(mult2_0_mult_out_rob_2_11), .ROB10(mult2_0_mult_out_rob_2_10),
        .ROB9(mult2_0_mult_out_rob_2_9), .ROB8(mult2_0_mult_out_rob_2_8),
        .ROB7(mult2_0_mult_out_rob_2_7), .ROB6(mult2_0_mult_out_rob_2_6),
        .ROB5(mult2_0_mult_out_rob_2_5), .ROB4(mult2_0_mult_out_rob_2_4),
        .ROB3(mult2_0_mult_out_rob_2_3), .ROB2(mult2_0_mult_out_rob_2_2),
        .ROB1(mult2_0_mult_out_rob_2_1), .ROB0(mult2_0_mult_out_rob_2_0),
        .ROC17(), .ROC16(), .ROC15(), .ROC14(), .ROC13(), .ROC12(), .ROC11(),
        .ROC10(), .ROC9(), .ROC8(), .ROC7(), .ROC6(), .ROC5(), .ROC4(),
        .ROC3(), .ROC2(), .ROC1(), .ROC0(), .P35(mult2_0_mult_out_p_2_35),
        .P34(mult2_0_mult_out_p_2_34), .P33(mult2_0_mult_out_p_2_33), .P32(mult2_0_mult_out_p_2_32),
        .P31(mult2_0_mult_out_p_2_31), .P30(mult2_0_mult_out_p_2_30), .P29(mult2_0_mult_out_p_2_29),
        .P28(mult2_0_mult_out_p_2_28), .P27(mult2_0_mult_out_p_2_27), .P26(mult2_0_mult_out_p_2_26),
        .P25(mult2_0_mult_out_p_2_25), .P24(mult2_0_mult_out_p_2_24), .P23(mult2_0_mult_out_p_2_23),
        .P22(mult2_0_mult_out_p_2_22), .P21(mult2_0_mult_out_p_2_21), .P20(mult2_0_mult_out_p_2_20),
        .P19(mult2_0_mult_out_p_2_19), .P18(mult2_0_mult_out_p_2_18), .P17(mult2_0_mult_out_p_2_17),
        .P16(mult2_0_mult_out_p_2_16), .P15(mult2_0_mult_out_p_2_15), .P14(mult2_0_mult_out_p_2_14),
        .P13(mult2_0_mult_out_p_2_13), .P12(mult2_0_mult_out_p_2_12), .P11(mult2_0_mult_out_p_2_11),
        .P10(mult2_0_mult_out_p_2_10), .P9(mult2_0_mult_out_p_2_9), .P8(mult2_0_mult_out_p_2_8),
        .P7(mult2_0_mult_out_p_2_7), .P6(mult2_0_mult_out_p_2_6), .P5(mult2_0_mult_out_p_2_5),
        .P4(mult2_0_mult_out_p_2_4), .P3(mult2_0_mult_out_p_2_3), .P2(mult2_0_mult_out_p_2_2),
        .P1(mult2_0_mult_out_p_2_1), .P0(mult2_0_mult_out_p_2_0), .SIGNEDP(mult2_0_mult_out_signedp_2));

    defparam dsp_mult_0.CLK3_DIV = "ENABLED" ;
    defparam dsp_mult_0.CLK2_DIV = "ENABLED" ;
    defparam dsp_mult_0.CLK1_DIV = "ENABLED" ;
    defparam dsp_mult_0.CLK0_DIV = "ENABLED" ;
    // defparam dsp_mult_0.HIGHSPEED_CLK = "NONE" ;
    // defparam dsp_mult_0.REG_INPUTC_RST = "RST0" ;
    // defparam dsp_mult_0.REG_INPUTC_CE = "CE0" ;
    defparam dsp_mult_0.REG_INPUTC_CLK = "NONE" ;
    defparam dsp_mult_0.SOURCEB_MODE = "B_SHIFT" ;
    // defparam dsp_mult_0.MULT_BYPASS = "DISABLED" ;
    // defparam dsp_mult_0.CAS_MATCH_REG = "FALSE" ;
    defparam dsp_mult_0.RESETMODE = "SYNC" ;
    defparam dsp_mult_0.GSR = "ENABLED" ;
    // defparam dsp_mult_0.REG_OUTPUT_RST = "RST0" ;
    // defparam dsp_mult_0.REG_OUTPUT_CE = "CE0" ;
    defparam dsp_mult_0.REG_OUTPUT_CLK = "NONE" ;
    defparam dsp_mult_0.REG_PIPELINE_RST = "RST0" ;
    defparam dsp_mult_0.REG_PIPELINE_CE = "CE0" ;
    defparam dsp_mult_0.REG_PIPELINE_CLK = "CLK0" ;
    defparam dsp_mult_0.REG_INPUTB_RST = "RST0" ;
    defparam dsp_mult_0.REG_INPUTB_CE = "CE0" ;
    defparam dsp_mult_0.REG_INPUTB_CLK = "CLK0" ;
    defparam dsp_mult_0.REG_INPUTA_RST = "RST0" ;
    defparam dsp_mult_0.REG_INPUTA_CE = "CE0" ;
    defparam dsp_mult_0.REG_INPUTA_CLK = "CLK0" ;
    MULT18X18D dsp_mult_0 (.A17(mdina4_r_17), .A16(mdina4_r_16), .A15(mdina4_r_15),
        .A14(mdina4_r_14), .A13(mdina4_r_13), .A12(mdina4_r_12), .A11(mdina4_r_11),
        .A10(mdina4_r_10), .A9(mdina4_r_9), .A8(mdina4_r_8), .A7(mdina4_r_7),
        .A6(mdina4_r_6), .A5(mdina4_r_5), .A4(mdina4_r_4), .A3(mdina4_r_3),
        .A2(mdina4_r_2), .A1(mdina4_r_1), .A0(mdina4_r), .B17(mdinb4_r_17),
        .B16(mdinb4_r_16), .B15(mdinb4_r_15), .B14(mdinb4_r_14), .B13(mdinb4_r_13),
        .B12(mdinb4_r_12), .B11(mdinb4_r_11), .B10(mdinb4_r_10), .B9(mdinb4_r_9),
        .B8(mdinb4_r_8), .B7(mdinb4_r_7), .B6(mdinb4_r_6), .B5(mdinb4_r_5),
        .B4(mdinb4_r_4), .B3(mdinb4_r_3), .B2(mdinb4_r_2), .B1(mdinb4_r_1),
        .B0(mdinb4_r), .C17(1'b0), .C16(1'b0), .C15(1'b0),
        .C14(1'b0), .C13(1'b0), .C12(1'b0), .C11(1'b0),
        .C10(1'b0), .C9(1'b0), .C8(1'b0), .C7(1'b0),
        .C6(1'b0), .C5(1'b0), .C4(1'b0), .C3(1'b0),
        .C2(1'b0), .C1(1'b0), .C0(1'b0), .SIGNEDA(1'b1),
        .SIGNEDB(1'b1), .SOURCEA(1'b0), .SOURCEB(1'b0), .CE0(CE0),
        .CE1(1'b1), .CE2(1'b1), .CE3(1'b1), .CLK0(CLK0),
        .CLK1(1'b0), .CLK2(1'b0), .CLK3(1'b0), .RST0(RST0),
        .RST1(1'b0), .RST2(1'b0), .RST3(1'b0), .SRIA17(1'b0),
        .SRIA16(1'b0), .SRIA15(1'b0), .SRIA14(1'b0), .SRIA13(1'b0),
        .SRIA12(1'b0), .SRIA11(1'b0), .SRIA10(1'b0), .SRIA9(1'b0),
        .SRIA8(1'b0), .SRIA7(1'b0), .SRIA6(1'b0), .SRIA5(1'b0),
        .SRIA4(1'b0), .SRIA3(1'b0), .SRIA2(1'b0), .SRIA1(1'b0),
        .SRIA0(1'b0), .SRIB17(1'b0), .SRIB16(1'b0), .SRIB15(1'b0),
        .SRIB14(1'b0), .SRIB13(1'b0), .SRIB12(1'b0), .SRIB11(1'b0),
        .SRIB10(1'b0), .SRIB9(1'b0), .SRIB8(1'b0), .SRIB7(1'b0),
        .SRIB6(1'b0), .SRIB5(1'b0), .SRIB4(1'b0), .SRIB3(1'b0),
        .SRIB2(1'b0), .SRIB1(1'b0), .SRIB0(1'b0), .SROA17(),
        .SROA16(), .SROA15(), .SROA14(), .SROA13(), .SROA12(), .SROA11(),
        .SROA10(), .SROA9(), .SROA8(), .SROA7(), .SROA6(), .SROA5(), .SROA4(),
        .SROA3(), .SROA2(), .SROA1(), .SROA0(), .SROB17(mult_shift_out_b_4_1_1_17),
        .SROB16(mult_shift_out_b_4_1_1_16), .SROB15(mult_shift_out_b_4_1_1_15),
        .SROB14(mult_shift_out_b_4_1_1_14), .SROB13(mult_shift_out_b_4_1_1_13),
        .SROB12(mult_shift_out_b_4_1_1_12), .SROB11(mult_shift_out_b_4_1_1_11),
        .SROB10(mult_shift_out_b_4_1_1_10), .SROB9(mult_shift_out_b_4_1_1_9),
        .SROB8(mult_shift_out_b_4_1_1_8), .SROB7(mult_shift_out_b_4_1_1_7),
        .SROB6(mult_shift_out_b_4_1_1_6), .SROB5(mult_shift_out_b_4_1_1_5),
        .SROB4(mult_shift_out_b_4_1_1_4), .SROB3(mult_shift_out_b_4_1_1_3),
        .SROB2(mult_shift_out_b_4_1_1_2), .SROB1(mult_shift_out_b_4_1_1_1),
        .SROB0(mult_shift_out_b_4_1_1_0), .ROA17(mult2_0_mult_out_roa_3_17),
        .ROA16(mult2_0_mult_out_roa_3_16), .ROA15(mult2_0_mult_out_roa_3_15),
        .ROA14(mult2_0_mult_out_roa_3_14), .ROA13(mult2_0_mult_out_roa_3_13),
        .ROA12(mult2_0_mult_out_roa_3_12), .ROA11(mult2_0_mult_out_roa_3_11),
        .ROA10(mult2_0_mult_out_roa_3_10), .ROA9(mult2_0_mult_out_roa_3_9),
        .ROA8(mult2_0_mult_out_roa_3_8), .ROA7(mult2_0_mult_out_roa_3_7),
        .ROA6(mult2_0_mult_out_roa_3_6), .ROA5(mult2_0_mult_out_roa_3_5),
        .ROA4(mult2_0_mult_out_roa_3_4), .ROA3(mult2_0_mult_out_roa_3_3),
        .ROA2(mult2_0_mult_out_roa_3_2), .ROA1(mult2_0_mult_out_roa_3_1),
        .ROA0(mult2_0_mult_out_roa_3_0), .ROB17(mult2_0_mult_out_rob_3_17),
        .ROB16(mult2_0_mult_out_rob_3_16), .ROB15(mult2_0_mult_out_rob_3_15),
        .ROB14(mult2_0_mult_out_rob_3_14), .ROB13(mult2_0_mult_out_rob_3_13),
        .ROB12(mult2_0_mult_out_rob_3_12), .ROB11(mult2_0_mult_out_rob_3_11),
        .ROB10(mult2_0_mult_out_rob_3_10), .ROB9(mult2_0_mult_out_rob_3_9),
        .ROB8(mult2_0_mult_out_rob_3_8), .ROB7(mult2_0_mult_out_rob_3_7),
        .ROB6(mult2_0_mult_out_rob_3_6), .ROB5(mult2_0_mult_out_rob_3_5),
        .ROB4(mult2_0_mult_out_rob_3_4), .ROB3(mult2_0_mult_out_rob_3_3),
        .ROB2(mult2_0_mult_out_rob_3_2), .ROB1(mult2_0_mult_out_rob_3_1),
        .ROB0(mult2_0_mult_out_rob_3_0), .ROC17(), .ROC16(), .ROC15(), .ROC14(),
        .ROC13(), .ROC12(), .ROC11(), .ROC10(), .ROC9(), .ROC8(), .ROC7(),
        .ROC6(), .ROC5(), .ROC4(), .ROC3(), .ROC2(), .ROC1(), .ROC0(), .P35(mult2_0_mult_out_p_3_35),
        .P34(mult2_0_mult_out_p_3_34), .P33(mult2_0_mult_out_p_3_33), .P32(mult2_0_mult_out_p_3_32),
        .P31(mult2_0_mult_out_p_3_31), .P30(mult2_0_mult_out_p_3_30), .P29(mult2_0_mult_out_p_3_29),
        .P28(mult2_0_mult_out_p_3_28), .P27(mult2_0_mult_out_p_3_27), .P26(mult2_0_mult_out_p_3_26),
        .P25(mult2_0_mult_out_p_3_25), .P24(mult2_0_mult_out_p_3_24), .P23(mult2_0_mult_out_p_3_23),
        .P22(mult2_0_mult_out_p_3_22), .P21(mult2_0_mult_out_p_3_21), .P20(mult2_0_mult_out_p_3_20),
        .P19(mult2_0_mult_out_p_3_19), .P18(mult2_0_mult_out_p_3_18), .P17(mult2_0_mult_out_p_3_17),
        .P16(mult2_0_mult_out_p_3_16), .P15(mult2_0_mult_out_p_3_15), .P14(mult2_0_mult_out_p_3_14),
        .P13(mult2_0_mult_out_p_3_13), .P12(mult2_0_mult_out_p_3_12), .P11(mult2_0_mult_out_p_3_11),
        .P10(mult2_0_mult_out_p_3_10), .P9(mult2_0_mult_out_p_3_9), .P8(mult2_0_mult_out_p_3_8),
        .P7(mult2_0_mult_out_p_3_7), .P6(mult2_0_mult_out_p_3_6), .P5(mult2_0_mult_out_p_3_5),
        .P4(mult2_0_mult_out_p_3_4), .P3(mult2_0_mult_out_p_3_3), .P2(mult2_0_mult_out_p_3_2),
        .P1(mult2_0_mult_out_p_3_1), .P0(mult2_0_mult_out_p_3_0), .SIGNEDP(mult2_0_mult_out_signedp_3));

    assign P[18] = mult2_alu_output_r_2_1_0;
    assign P[19] = mult2_alu_output_r_2_1_1;
    assign P[20] = mult2_alu_output_r_2_1_2;
    assign P[21] = mult2_alu_output_r_2_1_3;
    assign P[22] = mult2_alu_output_r_2_1_4;
    assign P[23] = mult2_alu_output_r_2_1_5;
    assign P[24] = mult2_alu_output_r_2_1_6;
    assign P[25] = mult2_alu_output_r_2_1_7;
    assign P[26] = mult2_alu_output_r_2_1_8;
    assign P[27] = mult2_alu_output_r_2_1_9;
    assign P[28] = mult2_alu_output_r_2_1_10;
    assign P[29] = mult2_alu_output_r_2_1_11;
    assign P[30] = mult2_alu_output_r_2_1_12;
    assign P[31] = mult2_alu_output_r_2_1_13;
    assign P[32] = mult2_alu_output_r_2_1_14;
    assign P[33] = mult2_alu_output_r_2_1_15;
    assign P[34] = mult2_alu_output_r_2_1_16;
    assign P[35] = mult2_alu_output_r_2_1_17;
    assign P[36] = mult2_alu_output_r_2_1_18;
    assign P[37] = mult2_alu_output_r_2_1_19;
    assign P[38] = mult2_alu_output_r_2_1_20;
    assign P[39] = mult2_alu_output_r_2_1_21;
    assign P[40] = mult2_alu_output_r_2_1_22;
    assign P[41] = mult2_alu_output_r_2_1_23;
    assign P[42] = mult2_alu_output_r_2_1_24;
    assign P[43] = mult2_alu_output_r_2_1_25;
    assign P[44] = mult2_alu_output_r_2_1_26;
    assign P[45] = mult2_alu_output_r_2_1_27;
    assign P[46] = mult2_alu_output_r_2_1_28;
    assign P[47] = mult2_alu_output_r_2_1_29;
    assign P[48] = mult2_alu_output_r_2_1_30;
    assign P[49] = mult2_alu_output_r_2_1_31;
    assign P[50] = mult2_alu_output_r_2_1_32;
    assign P[51] = mult2_alu_output_r_2_1_33;
    assign P[52] = mult2_alu_output_r_2_1_34;
    assign P[53] = mult2_alu_output_r_2_1_35;
    assign P[54] = mult2_alu_output_r_2_1_36;
    assign P[55] = mult2_alu_output_r_2_1_37;
    assign P[56] = mult2_alu_output_r_2_1_38;
    assign P[57] = mult2_alu_output_r_2_1_39;
    assign P[58] = mult2_alu_output_r_2_1_40;
    assign P[59] = mult2_alu_output_r_2_1_41;
    assign P[60] = mult2_alu_output_r_2_1_42;
    assign P[61] = mult2_alu_output_r_2_1_43;
    assign P[62] = mult2_alu_output_r_2_1_44;
    assign P[63] = mult2_alu_output_r_2_1_45;
    assign P[64] = mult2_alu_output_r_2_1_46;
    assign P[65] = mult2_alu_output_r_2_1_47;
    assign P[66] = mult2_alu_output_r_2_1_48;
    assign P[67] = mult2_alu_output_r_2_1_49;
    assign P[68] = mult2_alu_output_r_2_1_50;
    assign P[69] = mult2_alu_output_r_2_1_51;
    assign P[70] = mult2_alu_output_r_2_1_52;
    assign P[71] = mult2_alu_output_r_2_1_53;


    // exemplar begin
    // exemplar attribute FF_89 GSR ENABLED
    // exemplar attribute FF_88 GSR ENABLED
    // exemplar attribute FF_87 GSR ENABLED
    // exemplar attribute FF_86 GSR ENABLED
    // exemplar attribute FF_85 GSR ENABLED
    // exemplar attribute FF_84 GSR ENABLED
    // exemplar attribute FF_83 GSR ENABLED
    // exemplar attribute FF_82 GSR ENABLED
    // exemplar attribute FF_81 GSR ENABLED
    // exemplar attribute FF_80 GSR ENABLED
    // exemplar attribute FF_79 GSR ENABLED
    // exemplar attribute FF_78 GSR ENABLED
    // exemplar attribute FF_77 GSR ENABLED
    // exemplar attribute FF_76 GSR ENABLED
    // exemplar attribute FF_75 GSR ENABLED
    // exemplar attribute FF_74 GSR ENABLED
    // exemplar attribute FF_73 GSR ENABLED
    // exemplar attribute FF_72 GSR ENABLED
    // exemplar attribute FF_71 GSR ENABLED
    // exemplar attribute FF_70 GSR ENABLED
    // exemplar attribute FF_69 GSR ENABLED
    // exemplar attribute FF_68 GSR ENABLED
    // exemplar attribute FF_67 GSR ENABLED
    // exemplar attribute FF_66 GSR ENABLED
    // exemplar attribute FF_65 GSR ENABLED
    // exemplar attribute FF_64 GSR ENABLED
    // exemplar attribute FF_63 GSR ENABLED
    // exemplar attribute FF_62 GSR ENABLED
    // exemplar attribute FF_61 GSR ENABLED
    // exemplar attribute FF_60 GSR ENABLED
    // exemplar attribute FF_59 GSR ENABLED
    // exemplar attribute FF_58 GSR ENABLED
    // exemplar attribute FF_57 GSR ENABLED
    // exemplar attribute FF_56 GSR ENABLED
    // exemplar attribute FF_55 GSR ENABLED
    // exemplar attribute FF_54 GSR ENABLED
    // exemplar attribute FF_53 GSR ENABLED
    // exemplar attribute FF_52 GSR ENABLED
    // exemplar attribute FF_51 GSR ENABLED
    // exemplar attribute FF_50 GSR ENABLED
    // exemplar attribute FF_49 GSR ENABLED
    // exemplar attribute FF_48 GSR ENABLED
    // exemplar attribute FF_47 GSR ENABLED
    // exemplar attribute FF_46 GSR ENABLED
    // exemplar attribute FF_45 GSR ENABLED
    // exemplar attribute FF_44 GSR ENABLED
    // exemplar attribute FF_43 GSR ENABLED
    // exemplar attribute FF_42 GSR ENABLED
    // exemplar attribute FF_41 GSR ENABLED
    // exemplar attribute FF_40 GSR ENABLED
    // exemplar attribute FF_39 GSR ENABLED
    // exemplar attribute FF_38 GSR ENABLED
    // exemplar attribute FF_37 GSR ENABLED
    // exemplar attribute FF_36 GSR ENABLED
    // exemplar attribute FF_35 GSR ENABLED
    // exemplar attribute FF_34 GSR ENABLED
    // exemplar attribute FF_33 GSR ENABLED
    // exemplar attribute FF_32 GSR ENABLED
    // exemplar attribute FF_31 GSR ENABLED
    // exemplar attribute FF_30 GSR ENABLED
    // exemplar attribute FF_29 GSR ENABLED
    // exemplar attribute FF_28 GSR ENABLED
    // exemplar attribute FF_27 GSR ENABLED
    // exemplar attribute FF_26 GSR ENABLED
    // exemplar attribute FF_25 GSR ENABLED
    // exemplar attribute FF_24 GSR ENABLED
    // exemplar attribute FF_23 GSR ENABLED
    // exemplar attribute FF_22 GSR ENABLED
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
